/* eslint-disable */
// @ts-nocheck

// AUTO-GENERATED by api/scripts/dump_note_taker_settings_ts.py.
// Do not edit by hand — re-run the script after changing the Pydantic
// schema in core/domain/note_taker_settings/schemas.py.

export interface IntegrationConfluenceSchema {
  enabled?: boolean
  confluence_api_server?: string
  confluence_create_page_tool?: string
  space_key?: string
  parent_id?: string
  title_template?: string
}

export interface IntegrationSalesforceSchema {
  send_transcript_to_salesforce?: boolean
  salesforce_api_server?: string
  salesforce_stt_recording_tool?: string
}

export interface IntegrationsSchema {
  confluence?: IntegrationConfluenceSchema
  salesforce?: IntegrationSalesforceSchema
}

export interface PromptSettingSchema {
  enabled?: boolean
  prompt_template?: string
}

export interface NoteTakerSettings {
  subscription_recordings_ready?: boolean
  pipeline_id?: string
  send_number_of_speakers?: boolean
  accept_commands_from_non_organizer?: boolean
  create_knowledge_graph_embedding?: boolean
  knowledge_graph_system_name?: string
  keyterms?: string
  integration?: IntegrationsSchema
  chapters?: PromptSettingSchema
  summary?: PromptSettingSchema
  insights?: PromptSettingSchema
  post_transcription?: PromptSettingSchema
}

export const CURRENT_SETTINGS_REVISION = 1 as const
