import type { Component } from 'vue'
import {
  PhArchive,
  PhArrowClockwise,
  PhArrowCounterClockwise,
  PhArrowLeft,
  PhArrowRight,
  PhArrowSquareOut,
  PhArrowsIn,
  PhArrowsLeftRight,
  PhArrowsOut,
  PhBell,
  PhBookOpen,
  PhBrain,
  PhCalendar,
  PhCaretDown,
  PhCaretLeft,
  PhCaretLineLeft,
  PhCaretLineRight,
  PhCaretRight,
  PhCaretUp,
  PhChartBar,
  PhChartLine,
  PhChatCircle,
  PhChatCircleDots,
  PhChats,
  PhCheckCircle,
  PhCircle,
  PhClock,
  PhClipboardText,
  PhCloudArrowDown,
  PhCloudArrowUp,
  PhCode,
  PhColumns,
  PhCopy,
  PhCpu,
  PhDatabase,
  PhDotsSixVertical,
  PhDotsThree,
  PhDotsThreeVertical,
  PhDownload,
  PhEnvelope,
  PhEraser,
  PhExport,
  PhEye,
  PhEyeSlash,
  PhFile,
  PhFilePdf,
  PhFileSearch,
  PhFileText,
  PhFlask,
  PhFloppyDisk,
  PhFolder,
  PhFolderOpen,
  PhFootprints,
  PhFunnel,
  PhGearSix,
  PhGlobe,
  PhGraph,
  PhGridFour,
  PhHardDrives,
  PhHourglass,
  PhHouse,
  PhInfo,
  PhKey,
  PhLink,
  PhList,
  PhListBullets,
  PhListChecks,
  PhListNumbers,
  PhLock,
  PhMagicWand,
  PhMagnifyingGlass,
  PhMicrophone,
  PhMinus,
  PhNetwork,
  PhPaperPlaneRight,
  PhPaperclip,
  PhPencilSimple,
  PhPlay,
  PhPlug,
  PhPlus,
  PhPlusCircle,
  PhPlusSquare,
  PhPushPinSimple,
  PhPuzzlePiece,
  PhQuestion,
  PhRobot,
  PhScissors,
  PhShieldCheck,
  PhSignOut,
  PhSliders,
  PhSparkle,
  PhStack,
  PhStamp,
  PhStop,
  PhTable,
  PhTag,
  PhTextT,
  PhThumbsDown,
  PhThumbsUp,
  PhToggleRight,
  PhTrash,
  PhUpload,
  PhUser,
  PhUserCircle,
  PhVideo,
  PhWarning,
  PhWarningCircle,
  PhWrench,
  PhX,
} from '@phosphor-icons/vue'

export type KmPhosphorIconWeight = 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone'

export const PHOSPHOR_ICON_PREFIX = 'ph:'

const phosphorIconAliases: Record<string, Component> = {
  add: PhPlus,
  'add-circle': PhPlusCircle,
  'add-square': PhPlusSquare,
  ai: PhRobot,
  archive: PhArchive,
  article: PhFileText,
  attach: PhPaperclip,
  attach_file: PhPaperclip,
  'arrow-left': PhArrowLeft,
  'arrow-right': PhArrowRight,
  arrow_drop_down: PhCaretDown,
  arrow_drop_up: PhCaretUp,
  auto_awesome: PhMagicWand,
  back: PhArrowLeft,
  bell: PhBell,
  bolt: PhSparkle,
  book: PhBookOpen,
  brain: PhBrain,
  calendar: PhCalendar,
  calendar_month: PhCalendar,
  calendar_today: PhCalendar,
  category: PhTag,
  chart: PhChartBar,
  chat: PhChatCircleDots,
  chats: PhChats,
  check: PhCheckCircle,
  check_circle: PhCheckCircle,
  'chevron-down': PhCaretDown,
  'chevron-left': PhCaretLeft,
  'chevron-right': PhCaretRight,
  'chevron-up': PhCaretUp,
  chevron_left: PhCaretLeft,
  chevron_right: PhCaretRight,
  circle: PhCircle,
  clipboard: PhClipboardText,
  'clipboard-check': PhListChecks,
  'clipboard-list': PhClipboardText,
  clock: PhClock,
  'cloud-upload': PhCloudArrowUp,
  'cloud-download': PhCloudArrowDown,
  code: PhCode,
  columns: PhColumns,
  collapse: PhArrowsIn,
  content_copy: PhCopy,
  content_cut: PhScissors,
  copy: PhCopy,
  cpu: PhCpu,
  cut: PhScissors,
  database: PhDatabase,
  delete: PhTrash,
  delete_outline: PhTrash,
  description: PhFileText,
  dislike: PhThumbsDown,
  dots: PhDotsThree,
  drag: PhDotsSixVertical,
  drag_indicator: PhDotsSixVertical,
  download: PhDownload,
  edit: PhPencilSimple,
  email: PhEnvelope,
  eraser: PhEraser,
  error: PhWarningCircle,
  error_outline: PhWarningCircle,
  exchange_h: PhArrowsLeftRight,
  expand: PhArrowsOut,
  'external-link': PhArrowSquareOut,
  eye: PhEye,
  'eye-off': PhEyeSlash,
  expand_less: PhCaretUp,
  expand_more: PhCaretDown,
  export: PhExport,
  fact_check: PhListChecks,
  file: PhFile,
  'file-check': PhCheckCircle,
  file_copy: PhCopy,
  'file-pdf': PhFilePdf,
  'file-question': PhFileSearch,
  'file-search': PhFileSearch,
  'file-text': PhFileText,
  filter: PhFunnel,
  filter_list: PhFunnel,
  'first-page': PhCaretLineLeft,
  flask: PhFlask,
  folder: PhFolder,
  'folder-open': PhFolderOpen,
  folder_open: PhFolderOpen,
  format_list_numbered: PhListNumbers,
  format_quote: PhChatCircle,
  globe: PhGlobe,
  graph: PhGraph,
  grid_view: PhGridFour,
  history: PhArrowCounterClockwise,
  home: PhHouse,
  hourglass: PhHourglass,
  hourglass_top: PhHourglass,
  hub: PhGraph,
  info: PhInfo,
  insert_drive_file: PhFile,
  key: PhKey,
  'last-page': PhCaretLineRight,
  layers: PhStack,
  like: PhThumbsUp,
  link: PhLink,
  list: PhList,
  'list-numbered': PhListNumbers,
  logout: PhSignOut,
  lock: PhLock,
  magic: PhMagicWand,
  menu: PhList,
  microphone: PhMicrophone,
  minus: PhMinus,
  more: PhDotsThree,
  'more-vertical': PhDotsThreeVertical,
  more_vert: PhDotsThreeVertical,
  network: PhNetwork,
  o_add: PhPlus,
  o_add_circle: PhPlusCircle,
  o_category: PhTag,
  o_delete: PhTrash,
  o_edit: PhPencilSimple,
  o_hub: PhGraph,
  o_info: PhInfo,
  o_view_column: PhColumns,
  o_warning: PhWarning,
  open_in_new: PhArrowSquareOut,
  paper_plane: PhPaperPlaneRight,
  pdf: PhFilePdf,
  pen: PhPencilSimple,
  pencil: PhPencilSimple,
  pin: PhPushPinSimple,
  play: PhPlay,
  play_arrow: PhPlay,
  plug: PhPlug,
  plus: PhPlus,
  psychology: PhBrain,
  puzzle: PhPuzzlePiece,
  push_pin: PhPushPinSimple,
  question: PhQuestion,
  radio_button_unchecked: PhCircle,
  redo: PhArrowClockwise,
  refresh: PhArrowClockwise,
  reload: PhArrowClockwise,
  robot: PhRobot,
  save: PhFloppyDisk,
  scissors: PhScissors,
  search: PhMagnifyingGlass,
  'search-chart': PhFileSearch,
  send: PhPaperPlaneRight,
  server: PhDatabase,
  settings: PhSliders,
  'shield-check': PhShieldCheck,
  'sign-out': PhSignOut,
  smart_toy: PhRobot,
  stack: PhStack,
  stamp: PhStamp,
  steps: PhFootprints,
  stop: PhStop,
  storage: PhHardDrives,
  swap: PhArrowsLeftRight,
  sync: PhArrowClockwise,
  table: PhTable,
  'table-list': PhTable,
  tag: PhTag,
  tags: PhTag,
  text: PhTextT,
  text_fields: PhTextT,
  thumbtack: PhPushPinSimple,
  'thumbs-down': PhThumbsDown,
  'thumbs-up': PhThumbsUp,
  timeline: PhChartLine,
  toggle_on: PhToggleRight,
  'toggle-on': PhToggleRight,
  trash: PhTrash,
  tune: PhSliders,
  undo: PhArrowCounterClockwise,
  upload: PhUpload,
  user: PhUser,
  verified: PhCheckCircle,
  video: PhVideo,
  'video-file': PhVideo,
  view_list: PhListBullets,
  visibility: PhEye,
  visibility_off: PhEyeSlash,
  warning: PhWarning,
  wrench: PhWrench,
  x: PhX,

  'fa fa-arrow-right-arrow-left': PhArrowsLeftRight,
  'fa fa-check': PhCheckCircle,
  'fa fa-comment-dots': PhChatCircleDots,
  'fa fa-copy': PhCopy,
  'fa fa-external-link': PhArrowSquareOut,
  'fa fa-pen': PhPencilSimple,
  'fa fa-robot': PhRobot,
  'fa fa-times': PhX,
  'fa fa-xmark': PhX,
  'far fa-circle-check': PhCheckCircle,
  'far fa-copy': PhCopy,
  'far fa-file-alt': PhFileText,
  'far fa-plus-square': PhPlusSquare,
  'far fa-save': PhFloppyDisk,
  'far fa-trash-can': PhTrash,
  'fas fa-angle-left': PhCaretLeft,
  'fas fa-angle-right': PhCaretRight,
  'fas fa-arrow-left': PhArrowLeft,
  'fas fa-arrow-right': PhArrowRight,
  'fas fa-arrow-right-arrow-left': PhArrowsLeftRight,
  'fas fa-bars': PhList,
  'fas fa-bolt': PhSparkle,
  'fas fa-book': PhBookOpen,
  'fas fa-chart-column': PhChartBar,
  'fas fa-check': PhCheckCircle,
  'fas fa-check-circle': PhCheckCircle,
  'fas fa-chevron-down': PhCaretDown,
  'fas fa-chevron-left': PhCaretLeft,
  'fas fa-chevron-right': PhCaretRight,
  'fas fa-chevron-up': PhCaretUp,
  'fas fa-circle-exclamation': PhWarningCircle,
  'fas fa-circle-info': PhInfo,
  'fas fa-circle-nodes': PhGraph,
  'fas fa-clipboard-check': PhListChecks,
  'fas fa-clipboard-list': PhClipboardText,
  'fas fa-clock-rotate-left': PhArrowCounterClockwise,
  'fas fa-cloud-arrow-down': PhCloudArrowDown,
  'fas fa-cloud-arrow-up': PhCloudArrowUp,
  'fas fa-cloud-upload-alt': PhCloudArrowUp,
  'fas fa-code': PhCode,
  'fas fa-compress': PhArrowsIn,
  'fas fa-compress-alt': PhArrowsIn,
  'fas fa-cog': PhGearSix,
  'fas fa-cogs': PhGearSix,
  'fas fa-comment-dots': PhChatCircleDots,
  'fas fa-comments': PhChats,
  'fas fa-copy': PhCopy,
  'fas fa-database': PhDatabase,
  'fas fa-diagram-project': PhGraph,
  'fas fa-download': PhDownload,
  'fas fa-ellipsis-v': PhDotsThreeVertical,
  'fas fa-eraser': PhEraser,
  'fas fa-external-link-alt': PhArrowSquareOut,
  'fas fa-expand': PhArrowsOut,
  'fas fa-expand-alt': PhArrowsOut,
  'fas fa-eye': PhEye,
  'fas fa-eye-slash': PhEyeSlash,
  'fas fa-file': PhFile,
  'fas fa-file-circle-check': PhCheckCircle,
  'fas fa-file-circle-question': PhFileSearch,
  'fas fa-file-export': PhExport,
  'fas fa-file-lines': PhFileText,
  'fas fa-file-pdf': PhFilePdf,
  'fas fa-flask': PhFlask,
  'fas fa-folder': PhFolder,
  'fas fa-gear': PhGearSix,
  'fas fa-globe': PhGlobe,
  'fas fa-hard-drive': PhHardDrives,
  'fas fa-info-circle': PhInfo,
  'fas fa-layer-group': PhStack,
  'fas fa-link': PhLink,
  'fas fa-list-ul': PhListBullets,
  'fas fa-lock': PhLock,
  'fas fa-magnifying-glass-chart': PhFileSearch,
  'fas fa-microchip': PhCpu,
  'fas fa-microphone': PhMicrophone,
  'fas fa-paper-plane': PhPaperPlaneRight,
  'fas fa-paperclip': PhPaperclip,
  'fas fa-pen': PhPencilSimple,
  'fas fa-pencil': PhPencilSimple,
  'fas fa-play': PhPlay,
  'fas fa-plug': PhPlug,
  'fas fa-plus': PhPlus,
  'fas fa-project-diagram': PhGraph,
  'fas fa-puzzle-piece': PhPuzzlePiece,
  'fas fa-redo': PhArrowClockwise,
  'fas fa-rotate-right': PhArrowClockwise,
  'fas fa-save': PhFloppyDisk,
  'fas fa-search': PhMagnifyingGlass,
  'fas fa-server': PhDatabase,
  'fas fa-shield-alt': PhShieldCheck,
  'fas fa-shoe-prints': PhFootprints,
  'fas fa-sign-out-alt': PhSignOut,
  'fas fa-sliders': PhSliders,
  'fas fa-stamp': PhStamp,
  'fas fa-stop': PhStop,
  'fas fa-sync': PhArrowClockwise,
  'fas fa-table-columns': PhColumns,
  'fas fa-table-list': PhTable,
  'fas fa-tag': PhTag,
  'fas fa-tags': PhTag,
  'fas fa-thumbtack': PhPushPinSimple,
  'fas fa-thumbs-down': PhThumbsDown,
  'fas fa-thumbs-up': PhThumbsUp,
  'fas fa-times': PhX,
  'fas fa-times-circle': PhWarningCircle,
  'fas fa-trash': PhTrash,
  'fas fa-triangle-exclamation': PhWarning,
  'fas fa-undo': PhArrowCounterClockwise,
  'fas fa-upload': PhUpload,
  'fas fa-user': PhUser,
  'fas fa-user-circle': PhUserCircle,
  'fas fa-video': PhVideo,
  'fas fa-wand-magic-sparkles': PhMagicWand,
  'fas fa-wrench': PhWrench,
  'fas fa-xmark': PhX,
}

export const resolvePhosphorIcon = (name: string): Component | undefined => {
  const normalizedName = name.trim()
  const unprefixedName = normalizedName.startsWith(PHOSPHOR_ICON_PREFIX)
    ? normalizedName.slice(PHOSPHOR_ICON_PREFIX.length)
    : normalizedName

  return phosphorIconAliases[unprefixedName] ?? phosphorIconAliases[normalizedName]
}
