name: "Check Branch Name"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Checking branch name: $BRANCH_NAME"
          
          # Regex for allowed branch names
          # Allowed:
          # - main
          # - develop
          # - feature/*
          # - hotfix/*
          # - release/*
          # - experiment/*
          REGEX='^(feature|hotfix|release|experiment)\/.+|(main|develop)$'
          
          if [[ ! $BRANCH_NAME =~ $REGEX ]]; then
            echo "❌ Error: Branch name '$BRANCH_NAME' does not match the allowed pattern."
            echo "Allowed patterns:"
            echo "  - feature/..."
            echo "  - hotfix/..."
            echo "  - release/..."
            echo "  - experiment/..."
            echo "  - main"
            echo "  - develop"
            exit 1
          else
            echo "✅ Branch name is valid."
          fi
