<template>
  <km-popup-confirm :visible="showNewDialog" :title="m.dialog_newModelProvider()" :confirm-button-label="m.common_save()" :cancel-button-label="m.common_cancel()" :notification="m.hint_addSecurityModelProvider()" @confirm="createModelProvider" @cancel="$emit(&quot;cancel&quot;)">
    <div class="stack" data-gap="lg">
      <div class="flex-1">
        <div class="km-field text-secondary-text pb-xs pl-sm">{{ m.common_name() }}</div>
        <div class="full-width">
          <km-input ref="nameRef" v-model="name" data-test="name-input" height="30px" :rules="[required()]" :placeholder="m.placeholder_exampleMyOpenaiProvider()" />
        </div>
        <div class="km-description text-secondary-text pb-xs pl-sm">{{ m.hint_displayNameProvider() }}</div>
      </div>
      <div class="flex-1">
        <div class="km-field text-secondary-text pl-sm">{{ m.common_systemName() }}</div>
        <div class="full-width">
          <km-input ref="system_nameRef" v-model="system_name" data-test="system-name-input" height="30px" :rules="[required()]" :placeholder="m.placeholder_exampleMyOpenaiProviderSystemName()" />
        </div>
        <div class="km-description text-secondary-text pb-xs pl-sm">{{ m.hint_systemNameAutoGenerated() }}</div>
      </div>
      <div class="flex-1">
        <div class="km-field text-secondary-text pb-xs pl-sm">{{ m.label_apiType() }}</div>
        <div class="full-width">
          <km-select ref="typeRef" v-model="newRow.type" data-test="select-type" height="auto" min-height="36px" :placeholder="m.modelProviders_selectApiType()" :options="typeOptions" :rules="[required()]" emit-value map-options />
        </div>
        <div class="km-description text-secondary-text pb-xs pl-sm">{{ m.hint_apiTypeDescription() }}</div>
      </div>
      <div class="flex-1">
        <div class="km-field text-secondary-text pb-xs pl-sm">{{ m.label_endpoint() }}<span class="text-secondary-text ml-xs">{{ m.hint_optionalForOpenai() }}</span></div>
        <div class="full-width">
          <km-input v-model="newRow.endpoint" data-test="endpoint-input" height="30px" :placeholder="m.placeholder_exampleApiEndpoint()" :rules="[validateEndpoint]" />
        </div>
        <div class="km-description text-secondary-text pb-xs pl-sm">{{ endpointHint }}</div>
      </div>
    </div>
  </km-popup-confirm>
</template>

<script>
import { ref, reactive, computed } from 'vue'
import { m } from '@/paraglide/messages'
import { toUpperCaseWithUnderscores } from '@shared'
import { required } from '@/utils/validationRules'
import { useEntityQueries } from '@/queries/entities'
import { useRouter } from 'vue-router'
import { providerTypeOptions, providerEndpointHints } from '../../config/model_providers/providerTypes'
import { useSafeMutation } from '@/composables/useSafeMutation'
import { validateRef } from '@/utils/validateRef'

export default {
  props: {
    showNewDialog: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['cancel'],
  setup() {
    const queries = useEntityQueries()
    const createProvider = useSafeMutation(queries.provider.useCreate())
    const router = useRouter()

    const typeOptions = providerTypeOptions

    // Validate endpoint URL format
    const validateEndpoint = (val) => {
      if (!val) return true // Empty is OK (optional for some providers)
      // Check if it's a valid URL
      try {
        const url = new URL(val)
        if (!['http:', 'https:'].includes(url.protocol)) {
          return 'Endpoint must use http:// or https://'
        }
        // Check for trailing slash warning
        if (val.endsWith('/')) {
          return 'Endpoint should not have a trailing slash'
        }
        return true
      } catch {
        return 'Please enter a valid URL (e.g., https://api.example.com)'
      }
    }

    return {
      m,
      createProvider,
      router,
      required,
      validateEndpoint,
      newRow: reactive({
        name: '',
        system_name: '',
        type: '',
        category: 'llm', // Set category for Model Providers
        endpoint: '',
        connection_config: {},
        secrets_encrypted: {},
        metadata_info: {},
      }),
      autoChangeCode: ref(true),
      isMounted: ref(false),
      typeOptions,
    }
  },
  computed: {
    name: {
      get() {
        return this.newRow?.name || ''
      },
      set(val) {
        this.newRow.name = val
        if (this.autoChangeCode && this.isMounted) this.newRow.system_name = toUpperCaseWithUnderscores(val)
      },
    },
    system_name: {
      get() {
        return this.newRow?.system_name || ''
      },
      set(val) {
        this.newRow.system_name = val
        this.autoChangeCode = false
      },
    },
    endpointHint() {
      const type = this.newRow?.type
      return providerEndpointHints[type] || 'Provider API endpoint URL. Warning: changing endpoint later will clear all secrets.'
    },
  },
  mounted() {
    this.isMounted = true
  },
  beforeUnmount() {
    this.isMounted = false
    this.$emit('cancel')
  },
  methods: {
    validateFields() {
      const validStates = [validateRef(this.$refs.nameRef), validateRef(this.$refs.system_nameRef), validateRef(this.$refs.typeRef)]
      return !validStates.includes(false)
    },
    async createModelProvider() {
      if (!this.validateFields()) return

      const { success, data } = await this.createProvider.run(this.newRow)
      if (!success || !data?.id) return

      this.$router.push(`/model-providers/${data.id}`)
    },
  },
}
</script>
