<template lang="pug">
km-popup-confirm(
  :visible='showNewDialog',
  :title='m.dialog_newModelProvider()',
  :confirmButtonLabel='m.common_save()',
  :cancelButtonLabel='m.common_cancel()',
  :notification='m.hint_addSecurityModelProvider()',
  @confirm='createModelProvider',
  @cancel='$emit("cancel")'
)
  .column.q-gap-16
    .col
      .km-field.text-secondary-text.q-pb-xs.q-pl-8 {{ m.common_name() }}
      .full-width
        km-input(data-test='name-input', height='30px', v-model='name', ref='nameRef', :rules='[required()]', :placeholder='m.placeholder_exampleMyOpenaiProvider()')
      .km-description.text-secondary-text.q-pb-4.q-pl-8 {{ m.hint_displayNameProvider() }}

    .col
      .km-field.text-secondary-text.q-pl-8 {{ m.common_systemName() }}
      .full-width
        km-input(data-test='system-name-input', height='30px', v-model='system_name', ref='system_nameRef', :rules='[required()]', :placeholder='m.placeholder_exampleMyOpenaiProviderSystemName()')
      .km-description.text-secondary-text.q-pb-4.q-pl-8 {{ m.hint_systemNameAutoGenerated() }}

    .col
      .km-field.text-secondary-text.q-pb-xs.q-pl-8 {{ m.label_apiType() }}
      .full-width
        km-select(
          data-test='select-type',
          height='auto',
          minHeight='36px',
          placeholder='Select API Type',
          :options='typeOptions',
          v-model='newRow.type',
          ref='typeRef',
          :rules='[required()]',
          emit-value,
          mapOptions
        )
      .km-description.text-secondary-text.q-pb-4.q-pl-8 {{ m.hint_apiTypeDescription() }}

    .col
      .km-field.text-secondary-text.q-pb-xs.q-pl-8 {{ m.label_endpoint() }}
        span.text-secondary-text.q-ml-4 {{ m.hint_optionalForOpenai() }}
      .full-width
        km-input(
          data-test='endpoint-input',
          height='30px',
          v-model='newRow.endpoint',
          placeholder='https://api.example.com',
          :rules='[validateEndpoint]'
        )
      .km-description.text-secondary-text.q-pb-4.q-pl-8 {{ endpointHint }}
</template>

<script>
import { ref, reactive, computed } from 'vue'
import { m } from '@/paraglide/messages'
import { toUpperCaseWithUnderscores } from '@shared'
import { required } from '@/utils/validationRules'
import { useEntityQueries } from '@/queries/entities'
import { useRouter } from 'vue-router'
import { providerTypeOptions, providerEndpointHints } from '../../config/model_providers/providerTypes'

export default {
  props: {
    showNewDialog: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['cancel'],
  setup() {
    const queries = useEntityQueries()
    const { mutateAsync: createProvider } = queries.provider.useCreate()
    const router = useRouter()

    const typeOptions = providerTypeOptions

    // Validate endpoint URL format
    const validateEndpoint = (val) => {
      if (!val) return true // Empty is OK (optional for some providers)
      // Check if it's a valid URL
      try {
        const url = new URL(val)
        if (!['http:', 'https:'].includes(url.protocol)) {
          return 'Endpoint must use http:// or https://'
        }
        // Check for trailing slash warning
        if (val.endsWith('/')) {
          return 'Endpoint should not have a trailing slash'
        }
        return true
      } catch {
        return 'Please enter a valid URL (e.g., https://api.example.com)'
      }
    }

    return {
      m,
      createProvider,
      router,
      required,
      validateEndpoint,
      newRow: reactive({
        name: '',
        system_name: '',
        type: '',
        category: 'llm', // Set category for Model Providers
        endpoint: '',
        connection_config: {},
        secrets_encrypted: {},
        metadata_info: {},
      }),
      autoChangeCode: ref(true),
      isMounted: ref(false),
      typeOptions,
    }
  },
  computed: {
    name: {
      get() {
        return this.newRow?.name || ''
      },
      set(val) {
        this.newRow.name = val
        if (this.autoChangeCode && this.isMounted) this.newRow.system_name = toUpperCaseWithUnderscores(val)
      },
    },
    system_name: {
      get() {
        return this.newRow?.system_name || ''
      },
      set(val) {
        this.newRow.system_name = val
        this.autoChangeCode = false
      },
    },
    endpointHint() {
      const type = this.newRow?.type
      return providerEndpointHints[type] || 'Provider API endpoint URL. Warning: changing endpoint later will clear all secrets.'
    },
  },
  mounted() {
    this.isMounted = true
  },
  beforeUnmount() {
    this.isMounted = false
    this.$emit('cancel')
  },
  methods: {
    validateFields() {
      const validStates = [this.$refs.nameRef?.validate(), this.$refs.system_nameRef?.validate(), this.$refs.typeRef?.validate()]
      return !validStates.includes(false)
    },
    async createModelProvider() {
      if (!this.validateFields()) return

      const result = await this.createProvider(this.newRow)

      if (!result?.id) {
        return
      }

      this.$router.push(`/model-providers/${result.id}`)
    },
  },
}
</script>
