<template lang="pug">
.ba-border.bg-white.border-radius-12.q-pa-lg(style='min-width: 300px')
  km-section(title='Prompt template', subTitle='Prompt template defines the tone, format, length, etc of responses generated by LLM')
    .km-field.text-secondary-text.q-pb-xs.q-pl-8 Prompt template
    km-select(height='30px', placeholder='Standard Q&A Prompt', :options='prompts', v-model='generatePromptTemplate', hasDropdownSearch)
    .row.q-mt-sm
      .col-auto
        km-btn(
          flat,
          simple,
          :label='generatePromptTemplate ? "Open Prompt Template" : "Open Prompt Templates Library"',
          iconSize='16px',
          icon='fas fa-comment-dots',
          @click='generatePromptTemplate ? navigate(`prompt-templates/${generatePromptTemplateId}`) : navigate("prompt-templates")'
        )
</template>

<script>
import { computed } from 'vue'
import { useEntityQueries } from '@/queries/entities'
import { useRetrievalDetailStore } from '@/stores/entityDetailStores'

export default {
  emits: ['openTest'],
  setup() {
    const queries = useEntityQueries()
    const retrievalStore = useRetrievalDetailStore()
    const { data: promptListData } = queries.promptTemplates.useList()
    const promptItems = computed(() => promptListData.value?.items ?? [])
    return { retrievalStore, promptItems }
  },
  computed: {
    promptsWithId() {
      return (this.promptItems ?? []).map((item) => ({ label: item.name, value: item.system_name, id: item.id }))
    },
    generatePromptTemplateId() {
      return this.promptsWithId.find((el) => el.value == this.retrievalStore.activeVariant?.generate?.prompt_template)?.id
    },
    prompts() {
      return (this.promptItems ?? [])
        .map((item) => ({
          label: item.name,
          value: item.id,
          system_name: item.system_name,
          category: item.variants?.find((el) => el?.variant == item?.active_variant)?.category,
        }))
        .filter((el) => el.category === 'RAG')
    },
    propmt_name() {
      return (this.promptItems ?? []).find((el) => el.system_name === this.prompt_template)?.name
    },
    prompt_template() {
      return this.retrievalStore.activeVariant?.generate?.prompt_template
    },
    generatePromptTemplate: {
      get() {
        return this.propmt_name
      },
      set(value) {
        this.retrievalStore.updateNestedVariantProperty( { path: 'generate.prompt_template', value: value.system_name })
      },
    },
  },
  methods: {
    navigate(path = '') {
      if (this.$route.path !== `/${path}`) {
        this.$router.push(`/${path}`)
      }
    },
  },
}
</script>
