# type: ignore
"""source_scheduled_job_id

Revision ID: defd97efc36c
Revises: ca19414774ee
Create Date: 2025-12-19 16:44:55.886186+00:00

"""

from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = "defd97efc36c"
down_revision = "8eaf9d88a99f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_graph_sources",
        sa.Column(
            "schedule_job_id",
            GUID,
            nullable=True,
            comment="Foreign key to jobs (recurring sync schedule for this source)",
        ),
    )
    op.create_foreign_key(
        op.f("fk_knowledge_graph_sources_schedule_job_id_jobs"),
        "knowledge_graph_sources",
        "jobs",
        ["schedule_job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_knowledge_graph_sources_schedule_job_id"),
        "knowledge_graph_sources",
        ["schedule_job_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_knowledge_graph_sources_schedule_job_id"),
        table_name="knowledge_graph_sources",
    )
    op.drop_constraint(
        op.f("fk_knowledge_graph_sources_schedule_job_id_jobs"),
        "knowledge_graph_sources",
        type_="foreignkey",
    )
    op.drop_column("knowledge_graph_sources", "schedule_job_id")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""
    # Backfill schedule_job_id for sources that were scheduled before this column existed.
    #
    # We take the latest job per source based on jobs.created_at.
    op.execute(
        """
        UPDATE knowledge_graph_sources s
        SET schedule_job_id = (
            SELECT j.id
            FROM jobs j
            WHERE j.definition->'run_configuration'->>'type' = 'sync_knowledge_graph_source'
              AND j.definition->'run_configuration'->'params'->>'graph_id' = s.graph_id::text
              AND j.definition->'run_configuration'->'params'->>'source_id' = s.id::text
            ORDER BY j.created_at DESC
            LIMIT 1
        )
        WHERE s.schedule_job_id IS NULL
        """
    )


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
