# type: ignore
"""add_providers_table_and_update_relationships

Revision ID: b1fe5f31929b
Revises: 6525da98051b
Create Date: 2025-10-08 20:02:01.034305+00:00

"""

from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    EncryptedString,
    EncryptedText,
    GUID,
    ORA_JSONB,
    DateTimeUTC,
)
from sqlalchemy import Text  # noqa: F401
import advanced_alchemy.types
import advanced_alchemy.types.datetime
import advanced_alchemy.types.json
from sqlalchemy.dialects import postgresql
from core.db.models.mcp_server.mcp_server import EncryptedJsonB

if TYPE_CHECKING:
    pass

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = "b1fe5f31929b"
down_revision = "6525da98051b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Create providers table
    op.create_table(
        "providers",
        sa.Column(
            "type",
            sa.String(length=100),
            nullable=True,
            comment="Provider type (e.g., 'openai', 'azure', 'anthropic')",
        ),
        sa.Column(
            "connection_config",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "postgresql"),
            nullable=True,
            comment="Provider configuration (non-sensitive settings)",
        ),
        sa.Column(
            "secrets_encrypted",
            EncryptedJsonB(key="my-secret-key-tsmh5r"),
            nullable=True,
            comment="Encrypted credentials and sensitive connection data",
        ),
        sa.Column(
            "metadata_info",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "postgresql"),
            nullable=True,
            comment="Additional metadata about the provider",
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Entity name"),
        sa.Column("description", sa.Text, nullable=True, comment="Entity description"),
        sa.Column(
            "system_name",
            sa.String(length=255),
            nullable=False,
            comment="System name of the entity",
        ),
        sa.Column(
            "category", sa.String(length=255), nullable=True, comment="Entity category"
        ),
        sa.Column(
            "created_by",
            sa.String(length=36),
            nullable=True,
            comment="ID of the user who created the entity",
        ),
        sa.Column(
            "updated_by",
            sa.String(length=36),
            nullable=True,
            comment="ID of the user who last updated the entity",
        ),
        sa.Column("id", GUID, nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
        sa.UniqueConstraint("system_name", name=op.f("uq_providers_system_name")),
    )
    op.create_index(
        op.f("ix_providers_description"), "providers", ["description"], unique=False
    )
    op.create_index(op.f("ix_providers_name"), "providers", ["name"], unique=False)
    op.create_index(op.f("ix_providers_type"), "providers", ["type"], unique=False)

    # Step 2: Update ai_models table
    # Add new columns as nullable first
    op.add_column(
        "ai_models",
        sa.Column(
            "provider_system_name",
            sa.String(length=255),
            nullable=True,
            comment="Foreign key to provider system_name",
        ),
    )
    op.add_column(
        "ai_models",
        sa.Column(
            "provider_name",
            sa.String(length=100),
            nullable=True,
            comment="AI provider (e.g., azure_open_ai)",
        ),
    )

    # Copy data from old 'provider' column to new 'provider_name' column
    op.execute(
        "UPDATE ai_models SET provider_name = provider WHERE provider_name IS NULL"
    )

    # Now make provider_name NOT NULL
    op.alter_column("ai_models", "provider_name", nullable=False)

    # Drop old index and column
    op.drop_index(op.f("ix_ai_models_provider"), table_name="ai_models")
    op.drop_column("ai_models", "provider")

    # Create new indexes and foreign key
    op.create_index(
        op.f("ix_ai_models_provider_name"), "ai_models", ["provider_name"], unique=False
    )
    op.create_index(
        op.f("ix_ai_models_provider_system_name"),
        "ai_models",
        ["provider_system_name"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_ai_models_provider_system_name_providers"),
        "ai_models",
        "providers",
        ["provider_system_name"],
        ["system_name"],
        ondelete="CASCADE",
    )

    # Step 3: Update collections table
    op.add_column(
        "collections",
        sa.Column(
            "provider_system_name",
            sa.String(length=255),
            nullable=True,
            comment="Foreign key to provider system_name",
        ),
    )
    op.create_index(
        op.f("ix_collections_provider_system_name"),
        "collections",
        ["provider_system_name"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_collections_provider_system_name_providers"),
        "collections",
        "providers",
        ["provider_system_name"],
        ["system_name"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_collections_provider_system_name_providers"),
        "collections",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_collections_provider_system_name"), table_name="collections")
    op.drop_column("collections", "provider_system_name")
    op.add_column(
        "ai_models",
        sa.Column(
            "provider",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="AI provider (e.g., azure_open_ai)",
        ),
    )
    op.drop_constraint(
        op.f("fk_ai_models_provider_system_name_providers"),
        "ai_models",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_ai_models_provider_system_name"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_provider_name"), table_name="ai_models")
    op.create_index(
        op.f("ix_ai_models_provider"), "ai_models", ["provider"], unique=False
    )
    op.drop_column("ai_models", "provider_name")
    op.drop_column("ai_models", "provider_system_name")
    op.drop_index(op.f("ix_providers_type"), table_name="providers")
    op.drop_index(op.f("ix_providers_name"), table_name="providers")
    op.drop_index(op.f("ix_providers_description"), table_name="providers")
    op.drop_table("providers")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
