# type: ignore
"""initial migration

Revision ID: e8ba5f7594ec
Revises: 
Create Date: 2025-08-18 08:49:05.495732+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401
import advanced_alchemy.types
import advanced_alchemy.types.datetime
import advanced_alchemy.types.json
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = 'e8ba5f7594ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_embedding_co'), table_name='documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_metadata_gin'), table_name='documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc', postgresql_using='gin')
    op.drop_table('documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc')
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index(op.f('idx_documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48_embedding_co'), table_name='documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48_metadata_gin'), table_name='documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48', postgresql_using='gin')
    op.drop_table('documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48')
    op.drop_index(op.f('idx_documents_undefined_embedding_cosine'), table_name='documents_undefined', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_undefined_metadata_gin'), table_name='documents_undefined', postgresql_using='gin')
    op.drop_table('documents_undefined')
    op.drop_index(op.f('idx_documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_embedding_co'), table_name='documents_e76176e8_35a4_48f7_9502_953cafc9fcb9', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_metadata_gin'), table_name='documents_e76176e8_35a4_48f7_9502_953cafc9fcb9', postgresql_using='gin')
    op.drop_table('documents_e76176e8_35a4_48f7_9502_953cafc9fcb9')
    op.drop_index(op.f('idx_documents_d16e954b_959e_4795_9298_78b482006a77_embedding_co'), table_name='documents_d16e954b_959e_4795_9298_78b482006a77', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_d16e954b_959e_4795_9298_78b482006a77_metadata_gin'), table_name='documents_d16e954b_959e_4795_9298_78b482006a77', postgresql_using='gin')
    op.drop_table('documents_d16e954b_959e_4795_9298_78b482006a77')
    op.drop_index(op.f('idx_documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_embedding_co'), table_name='documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_metadata_gin'), table_name='documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344', postgresql_using='gin')
    op.drop_table('documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344')
    op.add_column('collections', sa.Column('job_id', sa.String(length=100), nullable=True, comment='Job ID associated with the collection'))
    op.drop_index(op.f('ix_evaluations_description'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_name'), table_name='evaluations')
    op.drop_constraint(op.f('uq_evaluations_system_name'), 'evaluations', type_='unique')
    op.drop_column('evaluations', 'name')
    op.drop_column('evaluations', 'description')
    op.drop_column('evaluations', 'updated_by')
    op.drop_column('evaluations', 'created_by')
    op.drop_column('evaluations', 'active_variant')
    op.drop_column('evaluations', 'system_name')
    op.drop_column('evaluations', 'variants')
    op.drop_column('evaluations', 'category')
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Entity category'))
    op.add_column('evaluations', sa.Column('variants', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True, comment='List of variants in JSON format'))
    op.add_column('evaluations', sa.Column('system_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='System name of the entity'))
    op.add_column('evaluations', sa.Column('active_variant', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Active variant name'))
    op.add_column('evaluations', sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='ID of the user who created the entity'))
    op.add_column('evaluations', sa.Column('updated_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='ID of the user who last updated the entity'))
    op.add_column('evaluations', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Entity description'))
    op.add_column('evaluations', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Entity name'))
    op.create_unique_constraint(op.f('uq_evaluations_system_name'), 'evaluations', ['system_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_evaluations_name'), 'evaluations', ['name'], unique=False)
    op.create_index(op.f('ix_evaluations_description'), 'evaluations', ['description'], unique=False)
    op.drop_column('collections', 'job_id')
    op.create_table('documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_pkey'))
    )
    op.create_index(op.f('idx_documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_metadata_gin'), 'documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_embedding_co'), 'documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_d16e954b_959e_4795_9298_78b482006a77',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_d16e954b_959e_4795_9298_78b482006a77_pkey'))
    )
    op.create_index(op.f('idx_documents_d16e954b_959e_4795_9298_78b482006a77_metadata_gin'), 'documents_d16e954b_959e_4795_9298_78b482006a77', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_d16e954b_959e_4795_9298_78b482006a77_embedding_co'), 'documents_d16e954b_959e_4795_9298_78b482006a77', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_e76176e8_35a4_48f7_9502_953cafc9fcb9',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_pkey'))
    )
    op.create_index(op.f('idx_documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_metadata_gin'), 'documents_e76176e8_35a4_48f7_9502_953cafc9fcb9', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_embedding_co'), 'documents_e76176e8_35a4_48f7_9502_953cafc9fcb9', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_undefined',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_undefined_pkey'))
    )
    op.create_index(op.f('idx_documents_undefined_metadata_gin'), 'documents_undefined', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_undefined_embedding_cosine'), 'documents_undefined', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48_pkey'))
    )
    op.create_index(op.f('idx_documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48_metadata_gin'), 'documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48_embedding_co'), 'documents_d911ad8e_3035_4945_a7ec_7cdb55d38b48', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_pkey'))
    )
    op.create_index(op.f('idx_documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_metadata_gin'), 'documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_embedding_co'), 'documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
