# type: ignore
"""initial migration

Revision ID: 663d04a21c65
Revises: 
Create Date: 2025-09-19 15:29:38.468269+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401
import advanced_alchemy.types
import advanced_alchemy.types.datetime
import advanced_alchemy.types.json
from sqlalchemy.dialects import postgresql
from advanced_alchemy.types import GUID
from core.db.models.mcp_server.mcp_server import EncryptedJsonB
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = '663d04a21c65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_servers',
    sa.Column('url', sa.String(), nullable=False, comment='API server URL'),
    sa.Column('security_scheme', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Security scheme configuration'),
    sa.Column('security_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Security values configuration'),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False, comment='SSL verification flag'),
    sa.Column('tools', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Tools configuration as array of dictionaries'),
    sa.Column('secrets_encrypted', EncryptedJsonB(key='my-secret-key'), nullable=True, comment='Encrypted secrets configuration'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_servers')),
    sa.UniqueConstraint('system_name', name=op.f('uq_api_servers_system_name'))
    )
    op.create_index(op.f('ix_api_servers_description'), 'api_servers', ['description'], unique=False)
    op.create_index(op.f('ix_api_servers_name'), 'api_servers', ['name'], unique=False)
    op.drop_index(op.f('idx_documents_9a846d89_99bc_4797_b9b5_370fa13a3325_embedding_co'), table_name='documents_9a846d89_99bc_4797_b9b5_370fa13a3325', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_9a846d89_99bc_4797_b9b5_370fa13a3325_metadata_gin'), table_name='documents_9a846d89_99bc_4797_b9b5_370fa13a3325', postgresql_using='gin')
    op.drop_table('documents_9a846d89_99bc_4797_b9b5_370fa13a3325')
    op.drop_index(op.f('idx_documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1_embedding_co'), table_name='documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1_metadata_gin'), table_name='documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1', postgresql_using='gin')
    op.drop_table('documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1')
    op.drop_index(op.f('idx_documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_embedding_co'), table_name='documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_metadata_gin'), table_name='documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344', postgresql_using='gin')
    op.drop_table('documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344')
    op.drop_index(op.f('idx_documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_embedding_co'), table_name='documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_metadata_gin'), table_name='documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc', postgresql_using='gin')
    op.drop_table('documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc')
    op.drop_index(op.f('idx_documents_f1905340_58e7_46c1_a014_45455c57c25b_embedding_co'), table_name='documents_f1905340_58e7_46c1_a014_45455c57c25b', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_f1905340_58e7_46c1_a014_45455c57c25b_metadata_gin'), table_name='documents_f1905340_58e7_46c1_a014_45455c57c25b', postgresql_using='gin')
    op.drop_table('documents_f1905340_58e7_46c1_a014_45455c57c25b')
    op.drop_index(op.f('idx_documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935_embedding_co'), table_name='documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935_metadata_gin'), table_name='documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935', postgresql_using='gin')
    op.drop_table('documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935')
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index(op.f('idx_documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9_embedding_co'), table_name='documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9_metadata_gin'), table_name='documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9', postgresql_using='gin')
    op.drop_table('documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9')
    op.drop_index(op.f('idx_documents_d16e954b_959e_4795_9298_78b482006a77_embedding_co'), table_name='documents_d16e954b_959e_4795_9298_78b482006a77', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_d16e954b_959e_4795_9298_78b482006a77_metadata_gin'), table_name='documents_d16e954b_959e_4795_9298_78b482006a77', postgresql_using='gin')
    op.drop_table('documents_d16e954b_959e_4795_9298_78b482006a77')
    op.drop_index(op.f('idx_documents_7bfc3213_11e5_4aeb_8183_cd346938841e_embedding_co'), table_name='documents_7bfc3213_11e5_4aeb_8183_cd346938841e', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_7bfc3213_11e5_4aeb_8183_cd346938841e_metadata_gin'), table_name='documents_7bfc3213_11e5_4aeb_8183_cd346938841e', postgresql_using='gin')
    op.drop_table('documents_7bfc3213_11e5_4aeb_8183_cd346938841e')
    op.drop_index(op.f('idx_documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7_embedding_co'), table_name='documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7_metadata_gin'), table_name='documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7', postgresql_using='gin')
    op.drop_table('documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7')
    op.drop_index(op.f('idx_documents_d20ca233_c668_41e2_a943_120bfedf23ae_embedding_co'), table_name='documents_d20ca233_c668_41e2_a943_120bfedf23ae', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_d20ca233_c668_41e2_a943_120bfedf23ae_metadata_gin'), table_name='documents_d20ca233_c668_41e2_a943_120bfedf23ae', postgresql_using='gin')
    op.drop_table('documents_d20ca233_c668_41e2_a943_120bfedf23ae')
    op.drop_index(op.f('idx_documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_embedding_co'), table_name='documents_e76176e8_35a4_48f7_9502_953cafc9fcb9', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_metadata_gin'), table_name='documents_e76176e8_35a4_48f7_9502_953cafc9fcb9', postgresql_using='gin')
    op.drop_table('documents_e76176e8_35a4_48f7_9502_953cafc9fcb9')
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_e76176e8_35a4_48f7_9502_953cafc9fcb9',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_pkey'))
    )
    op.create_index(op.f('idx_documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_metadata_gin'), 'documents_e76176e8_35a4_48f7_9502_953cafc9fcb9', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_e76176e8_35a4_48f7_9502_953cafc9fcb9_embedding_co'), 'documents_e76176e8_35a4_48f7_9502_953cafc9fcb9', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_d20ca233_c668_41e2_a943_120bfedf23ae',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_d20ca233_c668_41e2_a943_120bfedf23ae_pkey'))
    )
    op.create_index(op.f('idx_documents_d20ca233_c668_41e2_a943_120bfedf23ae_metadata_gin'), 'documents_d20ca233_c668_41e2_a943_120bfedf23ae', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_d20ca233_c668_41e2_a943_120bfedf23ae_embedding_co'), 'documents_d20ca233_c668_41e2_a943_120bfedf23ae', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7_pkey'))
    )
    op.create_index(op.f('idx_documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7_metadata_gin'), 'documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7_embedding_co'), 'documents_9c68394a_07ee_4bee_b84a_9f093b1b5dc7', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_7bfc3213_11e5_4aeb_8183_cd346938841e',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_7bfc3213_11e5_4aeb_8183_cd346938841e_pkey'))
    )
    op.create_index(op.f('idx_documents_7bfc3213_11e5_4aeb_8183_cd346938841e_metadata_gin'), 'documents_7bfc3213_11e5_4aeb_8183_cd346938841e', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_7bfc3213_11e5_4aeb_8183_cd346938841e_embedding_co'), 'documents_7bfc3213_11e5_4aeb_8183_cd346938841e', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_d16e954b_959e_4795_9298_78b482006a77',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_d16e954b_959e_4795_9298_78b482006a77_pkey'))
    )
    op.create_index(op.f('idx_documents_d16e954b_959e_4795_9298_78b482006a77_metadata_gin'), 'documents_d16e954b_959e_4795_9298_78b482006a77', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_d16e954b_959e_4795_9298_78b482006a77_embedding_co'), 'documents_d16e954b_959e_4795_9298_78b482006a77', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9_pkey'))
    )
    op.create_index(op.f('idx_documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9_metadata_gin'), 'documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9_embedding_co'), 'documents_c4cc72a7_2809_41ce_9d2d_7c140aeef9e9', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935_pkey'))
    )
    op.create_index(op.f('idx_documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935_metadata_gin'), 'documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935_embedding_co'), 'documents_dd04b20d_4a9d_4c55_afd3_cc16a198c935', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_f1905340_58e7_46c1_a014_45455c57c25b',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_f1905340_58e7_46c1_a014_45455c57c25b_pkey'))
    )
    op.create_index(op.f('idx_documents_f1905340_58e7_46c1_a014_45455c57c25b_metadata_gin'), 'documents_f1905340_58e7_46c1_a014_45455c57c25b', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_f1905340_58e7_46c1_a014_45455c57c25b_embedding_co'), 'documents_f1905340_58e7_46c1_a014_45455c57c25b', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_pkey'))
    )
    op.create_index(op.f('idx_documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_metadata_gin'), 'documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc_embedding_co'), 'documents_a39124aa_df9a_4ad1_8048_2b50e161d5dc', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_pkey'))
    )
    op.create_index(op.f('idx_documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_metadata_gin'), 'documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344_embedding_co'), 'documents_1d78439e_fa1d_471f_9088_3a3c1c6cc344', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1_pkey'))
    )
    op.create_index(op.f('idx_documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1_metadata_gin'), 'documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1_embedding_co'), 'documents_8394a5ba_0eb7_43b4_9530_d74d866c4cf1', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents_9a846d89_99bc_4797_b9b5_370fa13a3325',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_9a846d89_99bc_4797_b9b5_370fa13a3325_pkey'))
    )
    op.create_index(op.f('idx_documents_9a846d89_99bc_4797_b9b5_370fa13a3325_metadata_gin'), 'documents_9a846d89_99bc_4797_b9b5_370fa13a3325', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_9a846d89_99bc_4797_b9b5_370fa13a3325_embedding_co'), 'documents_9a846d89_99bc_4797_b9b5_370fa13a3325', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_api_servers_name'), table_name='api_servers')
    op.drop_index(op.f('ix_api_servers_description'), table_name='api_servers')
    op.drop_table('api_servers')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
