# type: ignore
"""initial migration

Revision ID: 6525da98051b
Revises: 
Create Date: 2025-10-01 07:14:29.976749+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401
import advanced_alchemy.types
import advanced_alchemy.types.datetime
import advanced_alchemy.types.json
from sqlalchemy.dialects import postgresql
from advanced_alchemy.types import GUID
from core.db.models.mcp_server.mcp_server import EncryptedJsonB
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = '6525da98051b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_conversations',
    sa.Column('agent', sa.String(length=255), nullable=True, comment='Agent identifier'),
    sa.Column('last_user_message_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Timestamp of last user message'),
    sa.Column('client_id', sa.String(length=255), nullable=True, comment='Client identifier'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='Trace identifier for request tracking'),
    sa.Column('analytics_id', sa.String(length=255), nullable=True, comment='Analytics identifier'),
    sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Variables in JSON format'),
    sa.Column('messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='List of messages in JSON format'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Conversation status'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_conversations'))
    )
    op.create_table('agents',
    sa.Column('active_variant', sa.String(length=255), nullable=True, comment='Active variant name'),
    sa.Column('variants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='List of variants in JSON format'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('system_name', name=op.f('uq_agents_system_name'))
    )
    op.create_index(op.f('ix_agents_description'), 'agents', ['description'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_table('ai_apps',
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='AI app settings'),
    sa.Column('tabs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Tabs configuration'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_apps')),
    sa.UniqueConstraint('system_name', name=op.f('uq_ai_apps_system_name'))
    )
    op.create_index(op.f('ix_ai_apps_description'), 'ai_apps', ['description'], unique=False)
    op.create_index(op.f('ix_ai_apps_name'), 'ai_apps', ['name'], unique=False)
    op.create_table('ai_models',
    sa.Column('provider', sa.String(length=100), nullable=False, comment='AI provider (e.g., azure_open_ai)'),
    sa.Column('ai_model', sa.String(length=255), nullable=False, comment='Model identifier (e.g., gpt-4o)'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='Human-readable model name'),
    sa.Column('json_mode', sa.Boolean(), nullable=False, comment='Supports JSON mode'),
    sa.Column('json_schema', sa.Boolean(), nullable=False, comment='Supports JSON schema validation'),
    sa.Column('tool_calling', sa.Boolean(), nullable=False, comment='Supports tool calling'),
    sa.Column('reasoning', sa.Boolean(), nullable=False, comment='Supports reasoning'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Model type (e.g., prompts)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Is this the default model for its type'),
    sa.Column('price_input', sa.String(length=20), nullable=True, comment='Price per input unit'),
    sa.Column('price_output', sa.String(length=20), nullable=True, comment='Price per output unit'),
    sa.Column('price_cached', sa.String(length=20), nullable=True, comment='Price per cached input unit'),
    sa.Column('price_standard_input_unit_count', sa.Integer(), nullable=True, comment='Standard input unit count for pricing'),
    sa.Column('price_cached_input_unit_count', sa.Integer(), nullable=True, comment='Cached input unit count for pricing'),
    sa.Column('price_standard_output_unit_count', sa.Integer(), nullable=True, comment='Standard output unit count for pricing'),
    sa.Column('price_input_unit_name', sa.String(length=50), nullable=True, comment='Input price unit name (e.g., tokens)'),
    sa.Column('price_output_unit_name', sa.String(length=50), nullable=True, comment='Output price unit name (e.g., tokens)'),
    sa.Column('resources', sa.String(length=500), nullable=True, comment='URL to pricing/documentation resources'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models')),
    sa.UniqueConstraint('system_name', name=op.f('uq_ai_models_system_name'))
    )
    op.create_index(op.f('ix_ai_models_ai_model'), 'ai_models', ['ai_model'], unique=False)
    op.create_index(op.f('ix_ai_models_description'), 'ai_models', ['description'], unique=False)
    op.create_index(op.f('ix_ai_models_display_name'), 'ai_models', ['display_name'], unique=False)
    op.create_index(op.f('ix_ai_models_name'), 'ai_models', ['name'], unique=False)
    op.create_index(op.f('ix_ai_models_provider'), 'ai_models', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_models_type'), 'ai_models', ['type'], unique=False)
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False, comment='API key name'),
    sa.Column('hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the API key'),
    sa.Column('value_masked', sa.String(length=20), nullable=False, comment="Masked version of the API key (e.g., '...Gpys')"),
    sa.Column('expires_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Expiration date/time'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the API key is active'),
    sa.Column('notes', sa.Text, nullable=True, comment='Additional notes about the API key'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_hash'), 'api_keys', ['hash'], unique=True)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_name'), 'api_keys', ['name'], unique=False)
    op.create_table('api_servers',
    sa.Column('url', sa.String(), nullable=False, comment='API server URL'),
    sa.Column('security_scheme', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Security scheme configuration'),
    sa.Column('security_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Security values configuration'),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False, comment='SSL verification flag'),
    sa.Column('tools', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Tools configuration as array of dictionaries'),
    sa.Column('secrets_encrypted', EncryptedJsonB(key='my-secret-key-tsmh5r'), nullable=True, comment='Encrypted secrets configuration'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_servers')),
    sa.UniqueConstraint('system_name', name=op.f('uq_api_servers_system_name'))
    )
    op.create_index(op.f('ix_api_servers_description'), 'api_servers', ['description'], unique=False)
    op.create_index(op.f('ix_api_servers_name'), 'api_servers', ['name'], unique=False)
    op.create_table('api_tools',
    sa.Column('api_provider', sa.String(length=255), nullable=True, comment='API provider name'),
    sa.Column('path', sa.String(length=500), nullable=True, comment='API endpoint path'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='HTTP method (GET, POST, etc.)'),
    sa.Column('mock', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Mock data configuration'),
    sa.Column('original_parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Original API parameters schema'),
    sa.Column('original_operation_definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Original OpenAPI operation definition'),
    sa.Column('active_variant', sa.String(length=255), nullable=True, comment='Active variant name'),
    sa.Column('variants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='List of variants in JSON format'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tools')),
    sa.UniqueConstraint('system_name', name=op.f('uq_api_tools_system_name'))
    )
    op.create_index(op.f('ix_api_tools_description'), 'api_tools', ['description'], unique=False)
    op.create_index(op.f('ix_api_tools_name'), 'api_tools', ['name'], unique=False)
    op.create_table('collections',
    sa.Column('type', sa.String(length=100), nullable=True, comment="Collection type (e.g., 'documents', 'images')"),
    sa.Column('ai_model', sa.String(length=100), nullable=True, comment="Model used for processing (e.g., 'AZURE_AI_TEXT-EMBEDDING-3-SMALL')"),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Source configuration for the collection'),
    sa.Column('chunking', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Chunking configuration for the collection'),
    sa.Column('indexing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Indexing configuration for the collection'),
    sa.Column('last_synced', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Last synced timestamp for the collection'),
    sa.Column('job_id', sa.String(length=100), nullable=True, comment='Job ID associated with the collection'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('system_name', name=op.f('uq_collections_system_name'))
    )
    op.create_index(op.f('ix_collections_description'), 'collections', ['description'], unique=False)
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.create_table('evaluation_sets',
    sa.Column('type', sa.String(length=100), nullable=True, comment="Type of evaluation set (e.g., 'test', 'validation')"),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='List of items in the evaluation set'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_sets')),
    sa.UniqueConstraint('system_name', name=op.f('uq_evaluation_sets_system_name'))
    )
    op.create_index(op.f('ix_evaluation_sets_description'), 'evaluation_sets', ['description'], unique=False)
    op.create_index(op.f('ix_evaluation_sets_name'), 'evaluation_sets', ['name'], unique=False)
    op.create_table('evaluations',
    sa.Column('job_id', sa.String(length=255), nullable=True, comment='Job identifier'),
    sa.Column('type', sa.String(length=100), nullable=True, comment='Evaluation type'),
    sa.Column('test_sets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='List of test sets used in evaluation'),
    sa.Column('started_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Evaluation start time'),
    sa.Column('finished_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Evaluation finish time'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Evaluation status'),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Error details if any'),
    sa.Column('tool', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Tool configuration used'),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Evaluation results with latency, score, usage data'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_table('jobs',
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Job definition including configuration and parameters'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current job status (e.g., Configuration, Completed, Running)'),
    sa.Column('next_run', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Next scheduled run time'),
    sa.Column('last_run', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Last execution time'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('transport', sa.String(), nullable=False, comment='Transport protocol (e.g., sse)'),
    sa.Column('url', sa.String(), nullable=False, comment='MCP server URL'),
    sa.Column('headers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='HTTP headers configuration'),
    sa.Column('tools', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Tools configuration'),
    sa.Column('secrets_encrypted', EncryptedJsonB(key='my-secret-key-tsmh5r'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_servers')),
    sa.UniqueConstraint('system_name', name=op.f('uq_mcp_servers_system_name'))
    )
    op.create_index(op.f('ix_mcp_servers_description'), 'mcp_servers', ['description'], unique=False)
    op.create_index(op.f('ix_mcp_servers_name'), 'mcp_servers', ['name'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.String(length=30), nullable=False, comment='Unique identifier for the metric'),
    sa.Column('feature_type', sa.String(length=100), nullable=True, comment="Feature type (e.g., 'agent', 'prompt', 'tool')"),
    sa.Column('feature_system_name', sa.String(length=255), nullable=True, comment="System name of the feature (e.g., 'DEMO_SALESFORCE_AGENT')"),
    sa.Column('feature_name', sa.String(length=255), nullable=True, comment="Human-readable feature name (e.g., 'Demo Salesforce Agent')"),
    sa.Column('feature_id', sa.String(length=255), nullable=True, comment="Unique identifier for the feature (e.g., 'agent_123')"),
    sa.Column('feature_variant', sa.String(length=100), nullable=True, comment="Feature variant identifier (e.g., 'variant_4')"),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='Associated trace identifier'),
    sa.Column('status', sa.String(length=100), nullable=True, comment="Execution status (e.g., 'success', 'error', 'failure')"),
    sa.Column('channel', sa.String(length=100), nullable=True, comment="Execution channel (e.g., 'production', 'development')"),
    sa.Column('source', sa.String(length=255), nullable=True, comment="Metric source (e.g., 'Runtime AI App', 'Web UI')"),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='User identifier'),
    sa.Column('consumer_name', sa.String(length=255), nullable=True, comment="Consumer name (e.g., 'DEMO_SALESFORCE_AGENT')"),
    sa.Column('consumer_type', sa.String(length=100), nullable=True, comment="Consumer type (e.g., 'agent', 'tool', 'prompt')"),
    sa.Column('start_time', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Metric execution start time'),
    sa.Column('end_time', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Metric execution end time'),
    sa.Column('latency', sa.Float(), nullable=True, comment='Execution latency in milliseconds'),
    sa.Column('conversation_id', sa.String(length=255), nullable=True, comment='Associated conversation identifier'),
    sa.Column('conversation_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Conversation metrics including tool call latency, topics, likes, dislikes, messages count'),
    sa.Column('cost', sa.Float(), nullable=True, comment='Total execution cost'),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Additional metric metadata and custom fields'),
    sa.Column('x_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Additional context attributes (e.g., organization ID)'),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics'))
    )
    op.create_index(op.f('ix_metrics_channel'), 'metrics', ['channel'], unique=False)
    op.create_index(op.f('ix_metrics_consumer_name'), 'metrics', ['consumer_name'], unique=False)
    op.create_index(op.f('ix_metrics_consumer_type'), 'metrics', ['consumer_type'], unique=False)
    op.create_index(op.f('ix_metrics_conversation_id'), 'metrics', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_metrics_cost'), 'metrics', ['cost'], unique=False)
    op.create_index(op.f('ix_metrics_end_time'), 'metrics', ['end_time'], unique=False)
    op.create_index(op.f('ix_metrics_feature_system_name'), 'metrics', ['feature_system_name'], unique=False)
    op.create_index(op.f('ix_metrics_feature_type'), 'metrics', ['feature_type'], unique=False)
    op.create_index(op.f('ix_metrics_feature_variant'), 'metrics', ['feature_variant'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_latency'), 'metrics', ['latency'], unique=False)
    op.create_index(op.f('ix_metrics_start_time'), 'metrics', ['start_time'], unique=False)
    op.create_index(op.f('ix_metrics_status'), 'metrics', ['status'], unique=False)
    op.create_index(op.f('ix_metrics_trace_id'), 'metrics', ['trace_id'], unique=False)
    op.create_index(op.f('ix_metrics_user_id'), 'metrics', ['user_id'], unique=False)
    op.create_table('prompts',
    sa.Column('active_variant', sa.String(length=255), nullable=True, comment='Active variant name'),
    sa.Column('variants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='List of variants in JSON format'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts')),
    sa.UniqueConstraint('system_name', name=op.f('uq_prompts_system_name'))
    )
    op.create_index(op.f('ix_prompts_description'), 'prompts', ['description'], unique=False)
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=False)
    op.create_table('rag_tools',
    sa.Column('active_variant', sa.String(length=255), nullable=True, comment='Active variant name'),
    sa.Column('variants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='List of variants in JSON format'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_tools')),
    sa.UniqueConstraint('system_name', name=op.f('uq_rag_tools_system_name'))
    )
    op.create_index(op.f('ix_rag_tools_description'), 'rag_tools', ['description'], unique=False)
    op.create_index(op.f('ix_rag_tools_name'), 'rag_tools', ['name'], unique=False)
    op.create_table('retrieval_tools',
    sa.Column('active_variant', sa.String(length=255), nullable=True, comment='Active variant name'),
    sa.Column('variants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='List of variants in JSON format'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text, nullable=True, comment='Entity description'),
    sa.Column('system_name', sa.String(length=255), nullable=False, comment='System name of the entity'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Entity category'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='ID of the user who created the entity'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='ID of the user who last updated the entity'),
    sa.Column('id', GUID, nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_tools')),
    sa.UniqueConstraint('system_name', name=op.f('uq_retrieval_tools_system_name'))
    )
    op.create_index(op.f('ix_retrieval_tools_description'), 'retrieval_tools', ['description'], unique=False)
    op.create_index(op.f('ix_retrieval_tools_name'), 'retrieval_tools', ['name'], unique=False)
    op.create_table('traces',
    sa.Column('id', sa.String(length=30), nullable=False, comment='Unique identifier for the trace'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Trace name (e.g., 'NPS Feedback Summary')"),
    sa.Column('type', sa.String(length=100), nullable=False, comment="Trace type (e.g., 'prompt-template', 'chat', 'span')"),
    sa.Column('status', sa.String(length=255), nullable=False, comment="Trace execution status (e.g., 'success', 'error', 'running')"),
    sa.Column('channel', sa.String(length=255), nullable=True, comment="Execution channel (e.g., 'production', 'development')"),
    sa.Column('source', sa.String(length=255), nullable=True, comment="Trace source (e.g., 'Runtime API', 'Web UI')"),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='User or API key identifier'),
    sa.Column('start_time', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Trace execution start time'),
    sa.Column('end_time', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True, comment='Trace execution end time'),
    sa.Column('latency', sa.Float(), nullable=True, comment='Execution latency in milliseconds'),
    sa.Column('cost_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Cost breakdown including chat, embed, rerank, and total costs'),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='Additional trace metadata and custom fields'),
    sa.Column('spans', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text), 'cockroachdb').with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text), 'postgresql'), nullable=True, comment='List of trace spans with detailed execution information'),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traces'))
    )
    op.create_index(op.f('ix_traces_channel'), 'traces', ['channel'], unique=False)
    op.create_index(op.f('ix_traces_end_time'), 'traces', ['end_time'], unique=False)
    op.create_index(op.f('ix_traces_id'), 'traces', ['id'], unique=False)
    op.create_index(op.f('ix_traces_latency'), 'traces', ['latency'], unique=False)
    op.create_index(op.f('ix_traces_name'), 'traces', ['name'], unique=False)
    op.create_index(op.f('ix_traces_start_time'), 'traces', ['start_time'], unique=False)
    op.create_index(op.f('ix_traces_status'), 'traces', ['status'], unique=False)
    op.create_index(op.f('ix_traces_type'), 'traces', ['type'], unique=False)
    op.create_index(op.f('ix_traces_user_id'), 'traces', ['user_id'], unique=False)
    op.drop_index(op.f('test_vectors_embedding_idx'), table_name='test_vectors', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('test_vectors')
    op.drop_index(op.f('embeddings_openai_embedding_idx'), table_name='embeddings_openai', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('embeddings_openai')
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings_openai',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('embeddings_openai_pkey')),
    comment='Table for storing OpenAI embeddings (1536 dimensions)'
    )
    op.create_index(op.f('embeddings_openai_embedding_idx'), 'embeddings_openai', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('test_vectors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_vectors_pkey')),
    comment='Test table for vector operations'
    )
    op.create_index(op.f('test_vectors_embedding_idx'), 'test_vectors', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_traces_user_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_type'), table_name='traces')
    op.drop_index(op.f('ix_traces_status'), table_name='traces')
    op.drop_index(op.f('ix_traces_start_time'), table_name='traces')
    op.drop_index(op.f('ix_traces_name'), table_name='traces')
    op.drop_index(op.f('ix_traces_latency'), table_name='traces')
    op.drop_index(op.f('ix_traces_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_end_time'), table_name='traces')
    op.drop_index(op.f('ix_traces_channel'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_retrieval_tools_name'), table_name='retrieval_tools')
    op.drop_index(op.f('ix_retrieval_tools_description'), table_name='retrieval_tools')
    op.drop_table('retrieval_tools')
    op.drop_index(op.f('ix_rag_tools_name'), table_name='rag_tools')
    op.drop_index(op.f('ix_rag_tools_description'), table_name='rag_tools')
    op.drop_table('rag_tools')
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_description'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_metrics_user_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_trace_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_status'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_start_time'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_latency'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_feature_variant'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_feature_type'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_feature_system_name'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_end_time'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_cost'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_conversation_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_consumer_type'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_consumer_name'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_channel'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_mcp_servers_name'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_description'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_evaluation_sets_name'), table_name='evaluation_sets')
    op.drop_index(op.f('ix_evaluation_sets_description'), table_name='evaluation_sets')
    op.drop_table('evaluation_sets')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_index(op.f('ix_collections_description'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_api_tools_name'), table_name='api_tools')
    op.drop_index(op.f('ix_api_tools_description'), table_name='api_tools')
    op.drop_table('api_tools')
    op.drop_index(op.f('ix_api_servers_name'), table_name='api_servers')
    op.drop_index(op.f('ix_api_servers_description'), table_name='api_servers')
    op.drop_table('api_servers')
    op.drop_index(op.f('ix_api_keys_name'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_models_type'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_provider'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_name'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_display_name'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_description'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_ai_model'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_ai_apps_name'), table_name='ai_apps')
    op.drop_index(op.f('ix_ai_apps_description'), table_name='ai_apps')
    op.drop_table('ai_apps')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_description'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('agent_conversations')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
