# type: ignore
"""add configs field to ai_models

Revision ID: f82c14db4dfc
Revises: 190948f54662
Create Date: 2025-10-13 05:24:42.342278+00:00

"""

from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    EncryptedString,
    EncryptedText,
    GUID,
    ORA_JSONB,
    DateTimeUTC,
)
from sqlalchemy import Text  # noqa: F401
import advanced_alchemy.types
import advanced_alchemy.types.datetime
import advanced_alchemy.types.json
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    pass

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = "f82c14db4dfc"
down_revision = "190948f54662"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_models",
        sa.Column(
            "configs",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "postgresql"),
            nullable=True,
            comment="Additional model configurations (e.g., vector_size for embeddings)",
        ),
    )
    op.alter_column(
        "providers",
        "type",
        existing_type=sa.VARCHAR(length=100),
        comment="Provider type (e.g., openai, azure_ai, azure_open_ai, oci, oci_llama, groq, datakom etc.)",
        existing_comment="Provider type (e.g., 'openai', 'azure', 'anthropic')",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "providers",
        "type",
        existing_type=sa.VARCHAR(length=100),
        comment="Provider type (e.g., 'openai', 'azure', 'anthropic')",
        existing_comment="Provider type (e.g., openai, azure_ai, azure_open_ai, oci, oci_llama, groq, datakom etc.)",
        existing_nullable=True,
    )
    op.drop_column("ai_models", "configs")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
