# type: ignore
"""knowledge_graph_metadata_extracted

Revision ID: 2d9361e34275
Revises: bb6c84b84a19
Create Date: 2026-01-12 20:50:06.392313+00:00

"""

from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types
import advanced_alchemy.types.datetime
import advanced_alchemy.types.json
import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    pass

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = "2d9361e34275"
down_revision = "bb6c84b84a19"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_graph_metadata_extractions",
        sa.Column("id", GUID, nullable=False),
        sa.Column(
            "graph_id", GUID, nullable=False, comment="Foreign key to knowledge_graphs"
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Metadata field name"
        ),
        sa.Column(
            "settings",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "postgresql"),
            nullable=False,
            comment="Metadata field settings",
        ),
        sa.Column(
            "sample_values",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "postgresql"),
            nullable=True,
            comment="Sample values observed for this field (best-effort, limited set)",
        ),
        sa.Column(
            "value_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Total number of values observed for this field (best-effort aggregation)",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["knowledge_graphs.id"],
            name=op.f(
                "fk_knowledge_graph_metadata_extractions_graph_id_knowledge_graphs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_knowledge_graph_metadata_extractions")
        ),
        sa.UniqueConstraint(
            "graph_id", "name", name="uq_knowledge_graph_metadata_extractions_name"
        ),
    )
    op.create_index(
        op.f("ix_knowledge_graph_metadata_extractions_graph_id"),
        "knowledge_graph_metadata_extractions",
        ["graph_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_graph_metadata_extractions_name"),
        "knowledge_graph_metadata_extractions",
        ["name"],
        unique=False,
    )
    op.alter_column(
        "knowledge_graph_metadata_discoveries",
        "origin",
        existing_type=sa.VARCHAR(length=50),
        comment="Origin where this field was observed (file, source)",
        existing_comment="Origin where this field was observed (file, source, llm)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "knowledge_graph_metadata_discoveries",
        "origin",
        existing_type=sa.VARCHAR(length=50),
        comment="Origin where this field was observed (file, source, llm)",
        existing_comment="Origin where this field was observed (file, source)",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_knowledge_graph_metadata_extractions_name"),
        table_name="knowledge_graph_metadata_extractions",
    )
    op.drop_index(
        op.f("ix_knowledge_graph_metadata_extractions_graph_id"),
        table_name="knowledge_graph_metadata_extractions",
    )
    op.drop_table("knowledge_graph_metadata_extractions")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
