# type: ignore
"""add_account_fields_to_teams_meeting

Revision ID: a0327aeb8cef
Revises: defd97efc36c
Create Date: 2026-01-08 13:23:25.449659+00:00

"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = "a0327aeb8cef"
down_revision = "defd97efc36c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams_meeting",
        sa.Column(
            "account_id",
            sa.Text,
            nullable=True,
            comment="Salesforce account id linked to this meeting",
        ),
    )
    op.add_column(
        "teams_meeting",
        sa.Column(
            "account_name",
            sa.Text,
            nullable=True,
            comment="Salesforce account name linked to this meeting",
        ),
    )
    op.alter_column(
        "teams_meeting",
        "meeting_id",
        existing_type=sa.TEXT(),
        comment="Teams meeting id from channel data",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "bot_id",
        existing_type=sa.TEXT(),
        comment="Bot app id installed in meeting",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "added_by_user_id",
        existing_type=sa.TEXT(),
        comment="Teams user id of the user who added the bot",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "added_by_aad_object_id",
        existing_type=sa.TEXT(),
        comment="AAD object id of the user who added the bot",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "added_by_display_name",
        existing_type=sa.TEXT(),
        comment="Display name of the user who added the bot",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "added_to_meeting_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the bot was added to the meeting",
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("uq_teams_meeting_chat_id"), "teams_meeting", type_="unique"
    )
    op.drop_constraint(
        op.f("uq_teams_meeting_graph_online_meeting_id"),
        "teams_meeting",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_teams_meeting_chat_id_bot_id", "teams_meeting", ["chat_id", "bot_id"]
    )
    op.create_unique_constraint(
        "uq_teams_meeting_graph_online_meeting_id_bot_id",
        "teams_meeting",
        ["graph_online_meeting_id", "bot_id"],
    )
    op.drop_column("teams_meeting", "sa_orm_sentinel")
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams_meeting",
        sa.Column("sa_orm_sentinel", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "uq_teams_meeting_graph_online_meeting_id_bot_id",
        "teams_meeting",
        type_="unique",
    )
    op.drop_constraint(
        "uq_teams_meeting_chat_id_bot_id", "teams_meeting", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_teams_meeting_graph_online_meeting_id"),
        "teams_meeting",
        ["graph_online_meeting_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_teams_meeting_chat_id"),
        "teams_meeting",
        ["chat_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "teams_meeting",
        "added_to_meeting_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp when the bot was added to the meeting",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "added_by_display_name",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Display name of the user who added the bot",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "added_by_aad_object_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="AAD object id of the user who added the bot",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "added_by_user_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Teams user id of the user who added the bot",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "bot_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Bot app id installed in meeting",
        existing_nullable=True,
    )
    op.alter_column(
        "teams_meeting",
        "meeting_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Teams meeting id from channel data",
        existing_nullable=True,
    )
    op.drop_column("teams_meeting", "account_name")
    op.drop_column("teams_meeting", "account_id")


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
