# type: ignore
"""add routing_config to ai_models

Revision ID: 7918f665581b
Revises: b465ecafa071
Create Date: 2026-03-03 15:50:43.956258+00:00

"""

from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    EncryptedString,
    EncryptedText,
    GUID,
    ORA_JSONB,
    DateTimeUTC,
)
from sqlalchemy import Text  # noqa: F401
import advanced_alchemy.types
import advanced_alchemy.types.datetime
import advanced_alchemy.types.json
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    pass

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = "7918f665581b"
down_revision = "b465ecafa071"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_models",
        sa.Column(
            "routing_config",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "postgresql"),
            nullable=True,
            comment="Routing config: rpm, tpm, fallback_models, cache, priority, weight",
        ),
    )
    op.drop_index(
        op.f("ix_knowledge_graph_sources_graph_id"),
        table_name="knowledge_graph_sources",
    )
    op.drop_index(
        op.f("ix_knowledge_graph_sources_schedule_job_id"),
        table_name="knowledge_graph_sources",
    )
    op.drop_index(
        op.f("ix_knowledge_graph_sources_type"), table_name="knowledge_graph_sources"
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_knowledge_graph_sources_type"),
        "knowledge_graph_sources",
        ["type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_graph_sources_schedule_job_id"),
        "knowledge_graph_sources",
        ["schedule_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_graph_sources_graph_id"),
        "knowledge_graph_sources",
        ["graph_id"],
        unique=False,
    )
    op.drop_column("ai_models", "routing_config")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
