# type: ignore
"""modify_note_taker_settings

Revision ID: bb6c84b84a19
Revises: e73a517576e8
Create Date: 2026-01-13 12:25:36.415596+00:00

"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    EncryptedString,
    EncryptedText,
    GUID,
    ORA_JSONB,
    DateTimeUTC,
)
from sqlalchemy import Text  # noqa: F401
import advanced_alchemy.types
import advanced_alchemy.types.datetime
import advanced_alchemy.types.json
from sqlalchemy.dialects import postgresql

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = "bb6c84b84a19"
down_revision = "e73a517576e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note_taker_settings",
        sa.Column("id", GUID, nullable=False),
        sa.Column(
            "config",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "postgresql"),
            nullable=True,
            comment="Settings in JSON format",
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Entity name"),
        sa.Column("description", sa.Text, nullable=True, comment="Entity description"),
        sa.Column(
            "system_name",
            sa.String(length=255),
            nullable=False,
            comment="System name of the entity",
        ),
        sa.Column(
            "category", sa.String(length=255), nullable=True, comment="Entity category"
        ),
        sa.Column(
            "created_by",
            sa.String(length=36),
            nullable=True,
            comment="ID of the user who created the entity",
        ),
        sa.Column(
            "updated_by",
            sa.String(length=36),
            nullable=True,
            comment="ID of the user who last updated the entity",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note_taker_settings")),
        sa.UniqueConstraint(
            "system_name", name=op.f("uq_note_taker_settings_system_name")
        ),
    )
    op.create_index(
        op.f("ix_note_taker_settings_description"),
        "note_taker_settings",
        ["description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_note_taker_settings_name"),
        "note_taker_settings",
        ["name"],
        unique=False,
    )
    op.drop_index(op.f("ix_settings_description"), table_name="settings")
    op.drop_index(op.f("ix_settings_name"), table_name="settings")
    op.drop_table("settings")
    op.add_column(
        "teams_meeting",
        sa.Column(
            "note_taker_settings_system_name",
            sa.Text,
            nullable=True,
            comment="Note taker settings system name associated with this meeting",
        ),
    )
    op.drop_column("teams_meeting", "last_recordings_check_at")
    op.drop_column("teams_meeting", "title")
    op.drop_column("teams_meeting", "join_url")
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams_meeting",
        sa.Column(
            "join_url",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Meeting join link",
        ),
    )
    op.add_column(
        "teams_meeting",
        sa.Column(
            "title",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Meeting subject/title",
        ),
    )
    op.add_column(
        "teams_meeting",
        sa.Column(
            "last_recordings_check_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="Last time recordings were checked for this meeting",
        ),
    )
    op.drop_column("teams_meeting", "note_taker_settings_system_name")
    op.create_table(
        "settings",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text),
            autoincrement=False,
            nullable=True,
            comment="Settings in JSON format",
        ),
        sa.Column(
            "name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Entity name",
        ),
        sa.Column(
            "description",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Entity description",
        ),
        sa.Column(
            "system_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="System name of the entity",
        ),
        sa.Column(
            "category",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Entity category",
        ),
        sa.Column(
            "created_by",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=True,
            comment="ID of the user who created the entity",
        ),
        sa.Column(
            "updated_by",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=True,
            comment="ID of the user who last updated the entity",
        ),
        sa.Column("sa_orm_sentinel", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint(
            "system_name",
            name=op.f("uq_settings_system_name"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_settings_name"), "settings", ["name"], unique=False)
    op.create_index(
        op.f("ix_settings_description"), "settings", ["description"], unique=False
    )
    op.drop_index(op.f("ix_note_taker_settings_name"), table_name="note_taker_settings")
    op.drop_index(
        op.f("ix_note_taker_settings_description"), table_name="note_taker_settings"
    )
    op.drop_table("note_taker_settings")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
