# type: ignore
"""add_settings_table

Revision ID: 39837e80ce55
Revises: a0327aeb8cef
Create Date: 2026-01-09 09:35:34.875619+00:00

"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    EncryptedString,
    EncryptedText,
    GUID,
    ORA_JSONB,
    DateTimeUTC,
)
from sqlalchemy import Text  # noqa: F401
import advanced_alchemy.types
import advanced_alchemy.types.datetime
import advanced_alchemy.types.json
from sqlalchemy.dialects import postgresql

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
# Additional type aliases for proper migration generation
sa.Text = Text


# revision identifiers, used by Alembic.
revision = "39837e80ce55"
down_revision = "a0327aeb8cef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", GUID, nullable=False),
        sa.Column(
            "config",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text), "postgresql"),
            nullable=True,
            comment="Settings in JSON format",
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Entity name"),
        sa.Column("description", sa.Text, nullable=True, comment="Entity description"),
        sa.Column(
            "system_name",
            sa.String(length=255),
            nullable=False,
            comment="System name of the entity",
        ),
        sa.Column(
            "category", sa.String(length=255), nullable=True, comment="Entity category"
        ),
        sa.Column(
            "created_by",
            sa.String(length=36),
            nullable=True,
            comment="ID of the user who created the entity",
        ),
        sa.Column(
            "updated_by",
            sa.String(length=36),
            nullable=True,
            comment="ID of the user who last updated the entity",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("system_name", name=op.f("uq_settings_system_name")),
    )
    op.create_index(
        op.f("ix_settings_description"), "settings", ["description"], unique=False
    )
    op.create_index(op.f("ix_settings_name"), "settings", ["name"], unique=False)
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_settings_name"), table_name="settings")
    op.drop_index(op.f("ix_settings_description"), table_name="settings")
    op.drop_table("settings")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
