<template>
  <km-dialog :model-value="showNewDialog" @cancel="$emit(&quot;cancel&quot;)">
    <km-card class="card-style" style="min-inline-size: 800px">
      <div class="km-card-section card-section-style">
        <div class="cluster">
          <div class="flex-1">
            <div class="km-heading-7">{{ m.agents_newTopic() }}</div>
          </div>
          <div class="flex-none">
            <km-btn icon="close" flat dense @click="$emit(&quot;cancel&quot;)" />
          </div>
        </div>
      </div>
      <div class="km-card-section card-section-style mb-md">
        <div class="cluster" data-justify="center">
          <km-stepper class="full-width" :steps="[ { step: 0, description: m.agents_topicSettingsStep(), icon: &quot;pen&quot; }, { step: 1, description: m.agents_addActionsStep(), icon: &quot;circle&quot; }, ]" :stepper="stepper" />
        </div>
        <div v-if="stepper === 0" class="stack full-width" data-gap="0">
          <km-notification-text class="mb-md" :notification="m.hint_topicNameDescription()" />
          <div class="km-field text-secondary-text pl-sm mb-md">{{ m.common_name() }}</div>
          <km-input ref="nameRef" v-model="name" class="mb-md" height="30px" />
          <div class="km-field text-secondary-text pl-sm">{{ m.agents_descriptionForLlmShort() }}</div>
          <km-input ref="descriptionRef" v-model="topic.description" class="mb-sm" type="textarea" rows="4" />
          <km-notification-text class="mb-md" :notification="m.hint_topicLlmInstructions()" />
          <div class="km-field text-secondary-text pl-sm">{{ m.common_systemName() }}</div>
          <km-input ref="system_nameRef" v-model="system_name" class="mb-md" height="30px">
            <div class="km-description text-secondary-text pb-xs">{{ m.hint_systemNameAutoGenerated() }}</div>
          </km-input>
        </div>
        <agents-tool-selection v-if="stepper === 1" v-model:selected="selected" />
        <div class="cluster mt-lg">
          <template v-if="stepper === 0">
            <div class="flex-none mr-sm">
              <km-btn flat :label="m.common_cancel()" tone="brand" @click="$emit(&quot;cancel&quot;)" />
            </div>
            <div class="km-space" />
            <div class="flex-none">
              <km-btn :label="m.common_next()" :disable="!readyForNext" @click="proceed" />
            </div>
          </template>
          <template v-else>
            <div class="flex-none mr-sm">
              <km-btn flat :label="m.common_cancel()" tone="brand" @click="$emit(&quot;cancel&quot;)" />
            </div>
            <div class="km-space" />
            <div class="flex-none mr-sm">
              <km-btn v-if="stepper != 0" flat :label="m.common_previous()" tone="brand" @click="stepper--" />
            </div>
            <div class="flex-none">
              <km-btn :label="m.common_create()" @click="create" />
            </div>
          </template>
        </div>
      </div>
    </km-card>
  </km-dialog>
</template>
<script>
import { ref, computed } from 'vue'
import { m } from '@/paraglide/messages'
import { useEntityQueries } from '@/queries/entities'
import { useCatalogOptions } from '@/queries/useCatalogOptions'
import { useAgentEntityDetail } from '@/composables/useAgentEntityDetail'
import { agentTopicActionsPopupColumns, agentTopicActionsAPIToolsPopupColumns } from '@/config/agents/topics'
import { toUpperCaseWithUnderscores } from '@shared'
import { notify } from '@shared/utils/notify'

export default {
  props: {
    showNewDialog: {
      default: false,
      type: Boolean,
    },
  },
  emits: ['cancel'],
  setup() {
    const queries = useEntityQueries()

    const { options: api_servers } = useCatalogOptions('api_servers')
    const { options: rag_tools } = useCatalogOptions('rag_tools')
    const { options: mcp_servers } = useCatalogOptions('mcp_servers')
    const { options: retrieval_tools } = useCatalogOptions('retrieval')

    const { data: promptTemplatesData } = queries.promptTemplates.useList()
    const prompt_templates = computed(() => promptTemplatesData.value?.items ?? [])

    const { activeVariant, updateVariantField } = useAgentEntityDetail()
    return {
      m,
      activeVariant,
      updateVariantField,
      searchString: ref(''),
      tabs: ref([
        { name: 'api', label: m.agents_apiTools() },
        { name: 'mcp_tool', label: m.agents_mcpTools() },
        { name: 'rag', label: m.agents_ragTools() },
        { name: 'retrieval', label: m.agents_retrievalTools() },
        { name: 'prompt_template', label: m.agents_promptTemplates() },
      ]),
      tab: ref('api'),
      selected: ref([]),
      topic: ref({
        name: '',
        description: '',
        system_name: '',
      }),
      stepper: ref(0),
      mcp_servers,
      api_servers,
      rag_tools,
      prompt_templates,
      retrieval_tools,
      agentTopicActionsPopupColumns,
      agentTopicActionsAPIToolsPopupColumns,
      autoChangeCode: ref(true),
      isMounted: ref(false),
    }
  },
  computed: {
    rows() {
      if (this.tab === 'rag') return this.getList(this.rag_tools, 'rag')
      if (this.tab === 'retrieval') return this.getList(this.retrieval_tools, 'retrieval')
      if (this.tab === 'prompt_template')
        return this.getList(
          (this.prompt_templates || []).filter((el) => el?.category === 'prompt_tool'),
          'prompt_template'
        )

      return []
    },
    name: {
      get() {
        return this.topic?.name || ''
      },
      set(val) {
        this.topic.name = val
        if (this.autoChangeCode && this.isMounted) this.topic.system_name = toUpperCaseWithUnderscores(val)
      },
    },
    system_name: {
      get() {
        return this.topic?.system_name || ''
      },
      set(val) {
        this.topic.system_name = val
        this.autoChangeCode = false
      },
    },
    instructions: {
      get() {
        return this.topic?.instructions || ''
      },
      set(val) {
        this.topic.instructions = val
      },
    },
    columns() {
      return Object.values(this.tab === 'api' ? this.agentTopicActionsAPIToolsPopupColumns : this.agentTopicActionsPopupColumns)
    },

    readyForNext() {
      return !!this.topic?.name && !!this.topic?.system_name
    },
    allSelected() {
      return this.apiTools.every((tool) => tool.selected === true)
    },
    topicSelectionPromptTemplate: {
      get() {
        return this.selectionPromptName
      },
      set(value) {
        this.updateVariantField('prompt_templates.classification', value.system_name)
      },
    },
  },
  mounted() {
    this.isMounted = true
  },
  beforeUnmount() {
    this.isMounted = false
    this.$emit('cancel')
  },
  methods: {
    selectRecord(row) {
      const index = this.selected.findIndex((item) => item?.id === row?.id)
      if (index === -1) {
        this.selected.push(row)
      } else {
        this.selected.splice(index, 1)
      }
    },
    getSelectedQtyByType(tab) {
      return this.selected.filter((item) => item.type === tab).length
    },
    create() {
      // get current topics
      const topics = this.activeVariant?.value?.topics || []
      const actions = this.selected.map((item) => {
        return {
          name: item.name,
          system_name: item.system_name,
          description: item.description,
          type: item.type,
          tool_system_name: item.system_name,
          function_name: (item.name || '').replace(/[^a-zA-Z0-9_\\.-]/g, ''),
          function_description: (item?.name ?? '') + ':' + (item?.description ?? ''),
          display_name: item.name,
          display_description: item.description,
          metadata: {
            created_at: new Date().toISOString(),
            modified_at: new Date().toISOString(),
          },
          tool_provider: item.tool_provider,
        }
      })
      const newTopic = {
        ...this.topic,
        metadata: {
          created_at: new Date().toISOString(),
          modified_at: new Date().toISOString(),
        },
        actions,
      }

      topics.push(newTopic)

      this.updateVariantField('topics', topics)

      notify.success(m.agents_topicAdded())

      this.$emit('cancel')
    },
    getList(list, type) {
      //  filter by searchString by all columns

      return list
        .map((item) => {
          return {
            id: item.id,
            name: item.name,
            description: item.description,
            system_name: item.system_name,
            type,
          }
        })
        .filter((item) => {
          return Object.values(item).some((value) => {
            return value.toString().toLowerCase().includes(this.searchString.toLowerCase())
          })
        })
    },
    updateTool(index, value) {
      Object.assign(this.apiTools[index], { selected: value })
    },
    proceed() {
      this.stepper++
    },
  },
}
</script>
<style>
.no-header thead {
  display: none;
}
</style>
