// Do NOT put `//` or `/* */` comments inside the braces of this import.
// @quasar/vite-plugin's import-rewriter uses a regex that rejects `/` and `*`
// (see node_modules/@quasar/vite-plugin/src/js-transform.js). If the regex
// fails, this import is left bare and resolves to `dist/quasar.client.js`,
// while other files (e.g. utils/notify.ts) get rewritten to deep paths like
// `quasar/src/plugins/notify/Notify.js`. Two evaluations of Quasar's plugin
// modules then coexist, install runs on one copy, and `Notify.create` is
// missing on the other — breaking notify.ts in production builds.
import {
  ClosePopup,
  Notify,
  Loading,
  Dialog,
  QLayout,
  QPageContainer,
  QPage,
  QToolbar,
  QBtn,
  QIcon,
  QList,
  QMenu,
  QItem,
  QItemSection,
  QItemLabel,
  QExpansionItem,
  QCard,
  QCardSection,
  QCardActions,
  QCheckbox,
  QDate,
  QDialog,
  QFab,
  QInnerLoading,
  QInput,
  QResizeObserver,
  QScrollObserver,
  QScrollArea,
  QSeparator,
  QSpinner,
  QTabPanels,
  QTabPanel,
  QTable,
  QTr,
  QTh,
  QTd,
  QTooltip,
  QLinearProgress,
  QSelect,
  QSpace,
} from 'quasar'

Notify.setDefaults({
  position: 'bottom-right',
  progress: true,
})

export default {
  config: {
    loading: {
      /* look at QuasarConfOptions from the API card */
    },
  },
  components: {
    // QAvatar,
    QLayout,
    // QHeader,
    // QDrawer,
    QPageContainer,
    QPage,
    // QToggle,
    QToolbar,
    // QToolbarTitle,
    QBtn,
    // QBtnDropdown,
    QIcon,
    QList,
    QMenu,
    QItem,
    QItemSection,
    QItemLabel,
    // QSlideTransition,
    QExpansionItem,
    QCard,
    QCardSection,
    QCardActions,
    QCheckbox,
    QDate,
    QDialog,
    QFab,
    QInnerLoading,
    // QForm,
    QInput,
    // QPopupProxy,
    // QSpinnerTail,
    QResizeObserver,
    QScrollObserver,
    QScrollArea,
    QSeparator,
    QSpinner,
    // QSplitter,
    // QTabs,
    // QTab,
    QTabPanels,
    QTabPanel,
    QTable,
    // QTime,
    QTr,
    QTh,
    QTd,
    QTooltip,
    QLinearProgress,
    // QPagination,
    QSelect,
    QSpace,
  },
  directives: {
    ClosePopup,
  },
  plugins: {
    Notify,
    Loading,
    Dialog,
  },
}
