<template lang="pug">
div
  km-section(title='Prompt template', subTitle='Prompt template defines the tone, format, length, etc of responses generated by LLM')
    .km-field.text-secondary-text.q-pb-xs.q-pl-8 Prompt template
    km-select(
      height='30px',
      placeholder='Standart Q&A Prompt',
      :options='promptTemplatesOptions',
      v-model='generatePromptTemplate',
      hasDropdownSearch,
      emit-value,
      map-options,
      option-value='system_name',
      :option-show='(item) => item?.category === "rag"'
    )
    .row.q-mt-sm
      .col-auto
        km-btn(
          flat,
          simple,
          :label='generatePromptTemplate ? "Open Prompt Template" : "Open Prompt Templates Library"',
          iconSize='16px',
          icon='fas fa-comment-dots',
          @click='generatePromptTemplate ? navigate(`prompt-templates/${generatePromptTemplateId}`) : navigate("prompt-templates")'
        )
</template>

<script>
import { useChroma } from '@shared'

export default {
  emits: ['openTest'],
  setup() {
    const { items: promptTemplateItems } = useChroma('promptTemplates')
    return {
      promptTemplateItems,
    }
  },
  computed: {
    generatePromptTemplateId() {
      return this.promptTemplatesOptions.find((el) => el.system_name == this.generatePromptTemplate)?.id
    },
    promptTemplatesOptions() {
      return (this.promptTemplateItems ?? []).map((item) => ({
        label: item.name,
        value: item.id,
        system_name: item.system_name,
        category: item?.category,
        id: item.id,
      }))
    },
    generatePromptTemplate: {
      get() {
        return this.$store.getters.ragVariant?.generate?.prompt_template
      },
      set(value) {
        this.$store.dispatch('updateNestedRagProperty', { path: 'generate.prompt_template', value })
      },
    },
  },
  methods: {
    navigate(path = '') {
      if (this.$route.path !== `/${path}`) {
        this.$router.push(`/${path}`)
      }
    },
  },
}
</script>
