/**
 * E2E Error Auto-Fix Script
 *
 * Reads error reports generated by Cypress e2e tests and uses Claude API
 * to suggest (or automatically apply) fixes for both frontend and backend errors.
 *
 * Usage:
 *   npx tsx scripts/fix-errors.ts             # analyze and print fixes
 *   npx tsx scripts/fix-errors.ts --apply     # analyze and apply fixes
 *   npx tsx scripts/fix-errors.ts --max-iter 3  # max auto-fix iterations (default: 3)
 *
 * Prerequisites:
 *   npm install @anthropic-ai/sdk tsx --save-dev   (or globally)
 *   export ANTHROPIC_API_KEY=sk-ant-...
 */

import Anthropic from '@anthropic-ai/sdk'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { execSync } from 'node:child_process'

// ─── Config ──────────────────────────────────────────────────────────────────

const PROJECT_ROOT = path.resolve(__dirname, '..')
const REPORTS_DIR = path.join(PROJECT_ROOT, 'reports')
const TESTS_DIR = path.join(REPORTS_DIR, 'tests')

const args = process.argv.slice(2)
const APPLY_FIXES = args.includes('--apply')
const MAX_ITER = (() => {
  const idx = args.indexOf('--max-iter')
  return idx !== -1 ? parseInt(args[idx + 1] ?? '3', 10) : 3
})()

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

// ─── Types ────────────────────────────────────────────────────────────────────

interface ErrorReport {
  testTitle: string
  testFile: string
  testStatus: string
  reportDir: string
  errorsMd: string
  frontendLog: string
  backendLog: string
}

interface FilePatch {
  filePath: string
  originalContent: string
  patchedContent: string
  explanation: string
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function log(msg: string) {
  console.log(msg)
}

function readFileIfExists(filePath: string): string {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : ''
}

function extractFilesFromReport(errorsMd: string, backendLog: string): string[] {
  const files = new Set<string>()

  // Extract from backend traceback: File "src/...", line N
  const tracebackMatches = errorsMd.matchAll(/File "([^"]+)", line \d+/g)
  for (const m of tracebackMatches) {
    const p = m[1]
    if (p.startsWith('/') && fs.existsSync(p)) files.add(p)
    else {
      const rel = path.join(PROJECT_ROOT, p)
      if (fs.existsSync(rel)) files.add(rel)
      // Try from api/src root
      const fromApi = path.join(PROJECT_ROOT, 'api', 'src', p)
      if (fs.existsSync(fromApi)) files.add(fromApi)
    }
  }

  // Extract backend filename:lineno patterns
  const backendEntries = backendLog
    .split('\n')
    .filter(Boolean)
    .map((l) => {
      try {
        return JSON.parse(l)
      } catch {
        return null
      }
    })
    .filter(Boolean)

  for (const entry of backendEntries) {
    if (entry.filename) {
      // structlog gives filename without full path — search for it
      const found = findFileInProject(entry.filename)
      if (found) files.add(found)
    }
  }

  // Extract frontend stack traces: at ComponentName.vue:N
  const vueMatches = errorsMd.matchAll(/at .+\(([^)]+\.(?:vue|ts|js)):\d+/g)
  for (const m of vueMatches) {
    const found = findFileInProject(path.basename(m[1]))
    if (found) files.add(found)
  }

  return [...files].slice(0, 10) // cap to avoid token explosion
}

function findFileInProject(filename: string): string | null {
  const searchDirs = [
    path.join(PROJECT_ROOT, 'api', 'src'),
    path.join(PROJECT_ROOT, 'web', 'apps', '@ipr', 'magnet-admin', 'src'),
    path.join(PROJECT_ROOT, 'web', 'apps', '@ipr', 'magnet-panel', 'src'),
    path.join(PROJECT_ROOT, 'web', 'packages'),
  ]
  for (const dir of searchDirs) {
    if (!fs.existsSync(dir)) continue
    try {
      const result = execSync(`find "${dir}" -name "${filename}" -type f 2>/dev/null`, {
        encoding: 'utf-8',
        timeout: 5000,
      })
        .trim()
        .split('\n')
        .filter(Boolean)
      if (result.length > 0) return result[0]
    } catch {
      // ignore
    }
  }
  return null
}

// ─── Core ─────────────────────────────────────────────────────────────────────

async function analyzeAndFix(report: ErrorReport): Promise<FilePatch[]> {
  const sourceFiles = extractFilesFromReport(report.errorsMd, report.backendLog)
  const testFileContent = readFileIfExists(path.join(PROJECT_ROOT, report.testFile))

  const sourceContext = sourceFiles
    .map((f) => {
      const relative = path.relative(PROJECT_ROOT, f)
      const content = readFileIfExists(f)
      return `### ${relative}\n\`\`\`\n${content.slice(0, 4000)}\n\`\`\``
    })
    .join('\n\n')

  const prompt = `You are a senior full-stack developer. A Cypress e2e test has produced errors.
Your task is to analyze the errors and return fixed source files.

## Error Report
${report.errorsMd}

## Test File (${report.testFile})
\`\`\`typescript
${testFileContent.slice(0, 2000)}
\`\`\`

## Source Files Referenced in Errors
${sourceContext || '_No source files could be resolved automatically._'}

## Instructions
1. Analyze ALL errors in the report (frontend and backend).
2. For each file that needs changes, return the COMPLETE fixed file content.
3. If a file does not need changes, do not include it.
4. Return your response as a JSON array with this structure:
[
  {
    "filePath": "relative/path/from/project/root",
    "patchedContent": "complete file content here",
    "explanation": "brief explanation of what was fixed"
  }
]
5. Return ONLY the JSON array, no other text.`

  log(`  Calling Claude API for: ${report.testTitle}`)

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 8192,
    messages: [{ role: 'user', content: prompt }],
  })

  const responseText = message.content
    .filter((b) => b.type === 'text')
    .map((b) => (b as { type: 'text'; text: string }).text)
    .join('')

  // Extract JSON from response
  const jsonMatch = responseText.match(/\[[\s\S]*\]/)
  if (!jsonMatch) {
    log(`  Warning: Claude returned no JSON patches for "${report.testTitle}"`)
    return []
  }

  let patches: { filePath: string; patchedContent: string; explanation: string }[]
  try {
    patches = JSON.parse(jsonMatch[0])
  } catch {
    log(`  Warning: Failed to parse Claude response as JSON`)
    return []
  }

  return patches.map((p) => ({
    filePath: path.join(PROJECT_ROOT, p.filePath),
    originalContent: readFileIfExists(path.join(PROJECT_ROOT, p.filePath)),
    patchedContent: p.patchedContent,
    explanation: p.explanation,
  }))
}

function applyPatches(patches: FilePatch[]): void {
  for (const patch of patches) {
    log(`  Applying fix to: ${path.relative(PROJECT_ROOT, patch.filePath)}`)
    log(`    Reason: ${patch.explanation}`)
    fs.writeFileSync(patch.filePath, patch.patchedContent, 'utf-8')
  }
}

function printPatches(patches: FilePatch[]): void {
  for (const patch of patches) {
    log(`\n  File: ${path.relative(PROJECT_ROOT, patch.filePath)}`)
    log(`  Fix:  ${patch.explanation}`)
    log(`  --- original (first 200 chars) ---`)
    log(`  ${patch.originalContent.slice(0, 200).replace(/\n/g, '\n  ')}`)
    log(`  --- patched (first 200 chars) ---`)
    log(`  ${patch.patchedContent.slice(0, 200).replace(/\n/g, '\n  ')}`)
  }
}

// ─── Entry point ──────────────────────────────────────────────────────────────

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('Error: ANTHROPIC_API_KEY environment variable is required.')
    process.exit(1)
  }

  if (!fs.existsSync(TESTS_DIR)) {
    log('No test reports found. Run Cypress tests first: cd web && yarn cypress run')
    process.exit(0)
  }

  // Collect all error reports
  const reportDirs = fs
    .readdirSync(TESTS_DIR)
    .map((name) => path.join(TESTS_DIR, name))
    .filter((p) => fs.statSync(p).isDirectory())

  if (reportDirs.length === 0) {
    log('No error reports found in reports/tests/. All tests passed!')
    process.exit(0)
  }

  const reports: ErrorReport[] = reportDirs
    .map((dir) => {
      const errorsMd = readFileIfExists(path.join(dir, 'errors.md'))
      const frontendLog = readFileIfExists(path.join(dir, 'frontend.log'))
      const backendLog = readFileIfExists(path.join(dir, 'backend.log'))

      // Parse metadata from errors.md
      const titleMatch = errorsMd.match(/\*\*Test:\*\* (.+)/)
      const fileMatch = errorsMd.match(/\*\*File:\*\* (.+)/)
      const statusMatch = errorsMd.match(/\*\*Status:\*\* (.+)/)

      return {
        testTitle: titleMatch?.[1]?.trim() ?? path.basename(dir),
        testFile: fileMatch?.[1]?.trim() ?? 'unknown',
        testStatus: statusMatch?.[1]?.trim() ?? 'unknown',
        reportDir: dir,
        errorsMd,
        frontendLog,
        backendLog,
      }
    })
    .filter((r) => r.testStatus.includes('FAILED') || r.frontendLog || r.backendLog)

  log(`\nFound ${reports.length} test report(s) with errors.\n`)

  if (APPLY_FIXES) {
    log(`Mode: AUTO-APPLY (max ${MAX_ITER} iteration(s))\n`)
  } else {
    log(`Mode: ANALYZE ONLY (use --apply to auto-apply fixes)\n`)
  }

  for (const report of reports) {
    log(`\n${'─'.repeat(60)}`)
    log(`Test: ${report.testTitle}`)
    log(`File: ${report.testFile}`)
    log(`${'─'.repeat(60)}`)

    for (let iter = 0; iter < MAX_ITER; iter++) {
      log(`\nIteration ${iter + 1}/${MAX_ITER}...`)

      const patches = await analyzeAndFix(report)

      if (patches.length === 0) {
        log('  No fixes suggested.')
        break
      }

      if (APPLY_FIXES) {
        applyPatches(patches)
        log(`  Applied ${patches.length} file(s). Re-run Cypress to verify.`)
        break
      } else {
        log(`  Suggested ${patches.length} fix(es):`)
        printPatches(patches)
        break
      }
    }
  }

  log(`\n${'─'.repeat(60)}`)
  log('Done. See reports/summary.md for the full test run overview.')
}

main().catch((err) => {
  console.error('Unexpected error:', err)
  process.exit(1)
})
