"""Generate TypeScript types from `NoteTakerSettingsSchema`.

The Pydantic schema in `core/domain/note_taker_settings/schemas.py` is the
single source of truth for the shape of `note_taker_settings.config`. This
script walks the JSON schema produced by `model_json_schema()` and emits a
TypeScript file that the admin frontend imports — keeping the two in sync
without an npm-side generator.

Usage:
    poetry run python scripts/dump_note_taker_settings_ts.py \\
        > ../web/apps/@ipr/magnet-admin/src/stores/types/noteTakerSettings.generated.ts

Re-run after any change to the Pydantic schemas. The generator handles the
shape we use today (bool/string/int + nested $ref objects); add support for
new types here as the schema grows.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

# Allow running as `python scripts/dump_note_taker_settings_ts.py` from anywhere.
_SRC = Path(__file__).resolve().parent.parent / "src"
sys.path.insert(0, str(_SRC))

from core.domain.note_taker_settings.schemas import (  # noqa: E402
    CURRENT_SETTINGS_REVISION,
    NoteTakerSettingsSchema,
)


_HEADER = """\
/* eslint-disable */
// @ts-nocheck

// AUTO-GENERATED by api/scripts/dump_note_taker_settings_ts.py.
// Do not edit by hand — re-run the script after changing the Pydantic
// schema in core/domain/note_taker_settings/schemas.py.
"""


def _ts_type(prop: dict[str, Any], defs: dict[str, Any]) -> str:
    """Return a TS type expression for a JSON Schema property."""
    if "$ref" in prop:
        ref_name = prop["$ref"].rsplit("/", 1)[-1]
        return ref_name

    if "anyOf" in prop:
        parts = [_ts_type(p, defs) for p in prop["anyOf"]]
        # JSON-schema "null" → TS null
        return " | ".join("null" if p == '"null"' or p == "null" else p for p in parts)

    json_type = prop.get("type")
    if json_type == "string":
        return "string"
    if json_type == "boolean":
        return "boolean"
    if json_type in ("integer", "number"):
        return "number"
    if json_type == "null":
        return "null"
    if json_type == "array":
        items = prop.get("items") or {}
        return f"Array<{_ts_type(items, defs)}>"
    if json_type == "object":
        # Schemas with extra="allow" produce free-form object — fall back to dict.
        return "Record<string, unknown>"

    # Fallback for unknown / mixed shapes.
    return "unknown"


def _emit_interface(name: str, schema: dict[str, Any], defs: dict[str, Any]) -> str:
    props: dict[str, Any] = schema.get("properties", {}) or {}
    required: set[str] = set(schema.get("required", []) or [])

    lines = [f"export interface {name} {{"]
    for key, prop in props.items():
        ts_type = _ts_type(prop, defs)
        optional = "" if key in required else "?"
        if "description" in prop:
            lines.append(f"  /** {prop['description']} */")
        lines.append(f"  {key}{optional}: {ts_type}")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    schema = NoteTakerSettingsSchema.model_json_schema(ref_template="#/$defs/{model}")
    defs = schema.get("$defs", {}) or {}

    out: list[str] = [_HEADER]

    # Each $defs entry → one interface (sub-schemas like PromptSettingSchema,
    # IntegrationConfluenceSchema, etc.).
    for name, sub in defs.items():
        out.append(_emit_interface(name, sub, defs))
        out.append("")

    # Top-level NoteTakerSettings interface.
    out.append(_emit_interface("NoteTakerSettings", schema, defs))
    out.append("")

    out.append(
        "export const CURRENT_SETTINGS_REVISION = "
        f"{CURRENT_SETTINGS_REVISION} as const\n"
    )

    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
